Granola-Team/mina-indexer

src/state/ledger/genesis.rs
Parse as u64 and do no float -> u64 conversion
=> Fix imprecise genesis account parsing

Cargo.lock, README.md, src/bin/mina-indexer-server.rs
Fixes server logging setting up `tracing_appender` incorrectly
* use match statement instead of if to assign non blocking writer and worker guard
* rename `--store-dir` to `--database-dir` to avoid name collision on short flag `-s` with `--startup-dir`
<hr>
Asana Tasks Referenced:
* https://app.asana.com/0/1203669416123378/1204789093923684/f
=> Server logging fix

src/bin/mina-indexer-server.rs, src/state/branch.rs, src/state/mod.rs, tests/state/dangling_branches/add_all_blocks.rs
Flamegraph exposed a lot of time being spent updating the `IndexerState::best_chain` field. Turns out, this was also causing a lot of unnecessary allocations too and the field is unnecessary!
This PR drastically improves performance
- removes the `best_chain` field from `IndexerState`
- replaces all uses of `best_chain` with a call to `root_branch.longest_chain()`
- modifies the server and tests accordingly
=> Remove best chain field from state

README.md, src/state/mod.rs
Fixes a bug where precomputed blocks lacking a `blockchain_length` in the filename cause an unreachable code error
* change comparison of `min_length` to use `.unwrap_or(0)` in case the field doesn't exist
* update the readme to fix some flags missing (`--root-hash` `--genesis-ledger` `--log-stdout`)
<hr>
Asana tasks referenced
* https://app.asana.com/0/1203669416123378/1204782760949370/f
=> Blockchain length unreachable

Cargo.lock, src/bin/mina-indexer-server.rs, src/block/store.rs, src/lib.rs, src/state/branch.rs, src/state/mod.rs, tests/state/dangling_branches/add_all_blocks.rs, tests/state/dangling_branches/add_same_block_twice.rs, tests/state/dangling_branches/complex/basic.rs, tests/state/dangling_branches/complex/multiple_branches.rs, tests/state/dangling_branches/complex/multiple_gaps.rs, tests/state/dangling_branches/simple/basic_multiple_branch.rs, tests/state/dangling_branches/simple/improper_forward.rs, tests/state/dangling_branches/simple/multiple_branch.rs, tests/state/dangling_branches/simple/proper_forward.rs, tests/state/dangling_branches/simple/reverse.rs, tests/state/root_branch/mod.rs
Adds support for pruning the root branch to a transition frontier of `k` blocks at a regular interval (number of blocks added)
* creates `Branch::prune_transition_frontier` which leverages Isaac's code in `Branch::merge_on` to prune the state tree when a branch has an ancestor list longer than `k`
* adds `prune_interval` field to `IndexerState` and calls `Branch::prune_transition_frontier` on the Root Branch for every `prune_interval` blocks added, or every block if no interval  is specified
* adds `info!` calls to `IndexerState::add_block` to log pruning
* changes the behavior of `IndexerState::add_block` to log duplicate blocks, and return `BlockNotAdded` instead of crashing
<hr>
Asana Tasks Referenced
* https://app.asana.com/0/1203669416123378/1204782760949366/f
* …
=> Transition Frontier Pruning

tests/block/receiver.rs
Fixes the `BlockReceiver` tests hanging on repeated runs of the test suite
* adds file directory checking and deletion before the test runs for:
** `detects_new_block_written`
** `detects_new_block_copied`
<hr>
Asana tasks referenced
* https://app.asana.com/0/1203669416123378/1204820393125448/f
=> fix BlockReceiver tests (at last)

src/server/mod.rs, src/state/branch.rs, src/state/mod.rs, tests/block/receiver.rs, tests/state/dangling_branches/add_all_blocks.rs, tests/state/dangling_branches/complex/basic.rs, tests/state/dangling_branches/complex/multiple_branches.rs, tests/state/dangling_branches/complex/multiple_gaps.rs, tests/state/dangling_branches/simple/basic_multiple_branch.rs, tests/state/dangling_branches/simple/improper_forward.rs, tests/state/dangling_branches/simple/multiple_branch.rs, tests/state/dangling_branches/simple/proper_forward.rs, tests/state/dangling_branches/simple/reverse.rs, tests/state/root_branch/simple_proper.rs
- removes the `leaves` field from the `Branch` struct in favor post order traversals
- adds a timeout to the block receiver test because it was still occasionally hanging
- updates other tests to reflect the `Branch` change
=> Remove leaves from `Branch`

src/bin/mainnet-test.rs, src/block/parser.rs, src/block/receiver.rs, src/client/mod.rs, src/lib.rs, src/server/mod.rs, src/state/branch.rs, src/state/mod.rs, tests/block/block_parser.rs, tests/block/store/add_and_get_blocks.rs, tests/state/dangling_branches/add_all_blocks.rs, tests/state/dangling_branches/add_same_block_twice.rs, tests/state/dangling_branches/complex/basic.rs, tests/state/dangling_branches/complex/multiple_branches.rs, tests/state/dangling_branches/complex/multiple_gaps.rs, tests/state/dangling_branches/simple/basic_multiple_branch.rs, tests/state/dangling_branches/simple/improper_forward.rs, tests/state/dangling_branches/simple/multiple_branch.rs, tests/state/dangling_branches/simple/proper_forward.rs, tests/state/dangling_branches/simple/reverse.rs, tests/state/ledger/apply_diff.rs, tests/state/ledger/diff_from_precomputed.rs, tests/state/root_branch/prune.rs, tests/state/root_branch/simple_proper.rs
This PR rethinks our initial ingestion of blocks. Instead of parsing and adding _all_ blocks in the startup dir to the witness tree, we instead _discover the longest canonical chain within these blocks_. Then we only parse and add _canonical_ blocks until we reach the highest canonical block in this directory, at which point we parse and add all successive blocks.
- implements the canonical chain discovery algorithm
- separates canonical and successive block paths in `BlockParser`
- adds `mode` and `phase` to `IndexerState`
- `mode` dictates whether non-canonical blocks are stored in the db
- `phase` allows us to change strategies depending on if we are initializing or watching
- we may want to experiment with a longer `prune_interval` while initializing and a shorter one while watching
- …
=> Filter canonical blocks on initial ingestion

src/block/parser.rs, src/server/mod.rs, src/state/ledger/genesis.rs, src/state/ledger/mod.rs, src/state/mod.rs, tests/block/block_parser.rs
This PR fixes the bootstrap ingestion performance problem
- instead of building the witness tree during bootstrapping, we simply calculate ledger diffs and apply them
- once we're done processing canonical blocks, we switch to building the witness tree
=> Short circuit canonical block diffs during bootstrap

src/block/mod.rs, src/block/precomputed.rs, src/state/branch.rs, src/state/mod.rs, tests/block/block_parser.rs
Adding field global_slot_since_genesis to precomputed block (corresponding struct and impl), which is consistent with mina-rs for global_slot_since_genesis. This adds support for staking ledgers (current and next) at epoch boundaries and therefore unblocking that issue. Also, some refactoring of tests and one new test.
=> Adding slot field global_slot_since_genesis to PC block 

src/block/precomputed.rs, src/state/mod.rs, src/store.rs
- Adds a `Key` interface
- Adds a `Transaction` interface to act as key variant
- Persists transactions when adding a block
The Transaction storage key is structured as follows - `T-{Height}-{Signature}`
We use the signature as unique part of the key until we have a better way to identify transactions (e.g. hash).
The height is padded to 12 digits for sequential iteration.
=> feat: index transactions

Cargo.lock, Cargo.toml, src/bin/mainnet-test.rs, src/bin/mina-indexer.rs, src/gql/mod.rs, src/gql/root.rs, src/gql/schema/mod.rs, src/gql/schema/transaction.rs, src/lib.rs, src/server/mod.rs, src/state/mod.rs, src/store.rs
This PR implements a GQL server with minimal structural changes.
- Adds `actix` & `juniper`
- Restructures RDB usage to be shared between services 
- Adds a transactions query with the following filters:
```rust
pub struct TransactionQueryInput {
pub from: Option<String>,
pub to: Option<String>,
pub memo: Option<String>,
pub date_time_gte: Option<DateTime<Utc>>,
pub date_time_lte: Option<DateTime<Utc>>,
}
```
=> feat: added gql server & transactions query

src/state/ledger/account.rs, src/state/ledger/command.rs, src/state/ledger/diff/account.rs, src/state/ledger/mod.rs, tests/state/ledger/diff_from_precomputed.rs
Adding additional testing where I set the initial balance of the account explicitly before applying the diffs. This allows us to verify that the post-balance calculation logic is working as expected. By explicitly setting the initial balance and applying the diff with a specific amount, we can check if the resulting balance in the ledger matches our expectations. These tests ensure that the ledger takes into account the existing balance of the account when applying the diffs and correctly updates the balance based on the diff type (deposit or deduction). Whereas the previous tests focus on testing the application of account diffs, while the new tests extend the testing to include the verification of balance calculations based on the initial balance and the applied diff. …
=> Testing post-balance calculation logic

README.md, src/client/mod.rs, src/server/mod.rs, src/state/branch.rs, src/state/mod.rs, tests/state/dangling_branches/add_all_blocks.rs, tests/state/dangling_branches/add_same_block_twice.rs, tests/state/dangling_branches/complex/multiple_branches.rs, tests/state/dangling_branches/simple/proper_forward.rs, tests/state/dangling_branches/simple/reverse.rs
These are commits independent of and cherry-picked from the `snapshot` branch.
- adds a default `--num 10` for the `best-chain` command
- improves the `best-chain` calculation by fetching blocks from the db
- uses `Display` over `Debug` for displaying `IndexerState` and `Branch`
- updates README with correct CLI flags
=> Best chain improvements

Cargo.lock, src/gql/schema/transaction.rs
This PR adds support for the `AND` / `OR` operators on the transactions query, as well as DateTime filtering.
Run the following query in GraphiQL:
```gql
query Transactions {
transactions(limit: 10000, query: {canonical: true, OR: [{memo: "E4YM2vTHhWEg66xpj52JErHUBU4pZ1yageL4TVDDpTTSsv8mK6YaH"}, {memo: "E4YvxPhU2fXZvSLeTBN7tZVrA2FmxyqWfxr6eXJfpdgQ4VLQuW7Ub"}], dateTime_gte: "2022-01-01T00:00:00Z", dateTime_lte: "2022-12-31T00:00:00Z"}, sortBy: NONCE_DESC) {
memo
canonical
from
to
blockHeight
dateTime
}
}
=> feat: Add logical operators to transactions query

Cargo.lock, Cargo.toml, src/block/signed_command.rs
Follows ChainSafe's [signed command hash](https://github.com/ChainSafe/mina-signer-wasm/blob/48286bd00d0e62d8a2783194dbc5c73b7f73e516/src/client.rs#L292)
- makes `SignedCommand` a wrapper around mina-rs's `SignedCommandV1`
- adds transaction/signed command hash
- adds unit test
=> WIP Transaction hash

src/bin/mainnet-test.rs, src/block/parser.rs, src/lib.rs, src/server.rs
- fixes `std::time::Duration` display error
- adds logging and block length filtering to the `mainnet-test` binary
=> Mainnet test logging and filtering

src/bin/mina-indexer.rs
Adds functionality to `mina-indexer` to delete the database dir and create a new on if it exists
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205196244475473
=> Delete existing RocksDB dir

Cargo.lock, Cargo.toml, src/gql/schema/transaction.rs, src/store.rs
Modified the format of the TransactionKey to make use of the fact that base32hex encoded numeric values maintain sort ordering. This allows us to efficiently seek to the lower bound of the transaction dataset. Where previously we did a naive full scan of all the dataset.
=> Transactions datetime index

Cargo.lock, Cargo.toml, src/bin/mina-indexer.rs, src/block/mod.rs, src/gql/mod.rs, src/server.rs, src/state/branch.rs, src/state/mod.rs, src/state/summary.rs
Creates a query interface into the `server::{initialize, run}` functions to allow for testing of the Mina Indexer in situ
* Create `MinaIndexer` class to serve as the interface into a running indexer
* separate `server::run` into `server::run` and `server::initialize`
* add various channels to `MinaIndexer` and `server::run` to query the `IndexerState` while it is running
<hr>
Asana Tasks Referenced
* https://app.asana.com/0/1203669416123378/1205355603199909/f
* https://app.asana.com/0/1203669416123378/1205188527548527/f
=> Server Testability

src/client.rs, src/server.rs, src/state/ledger/account.rs
Verify the account returns mina instead of nanomina
```sh
cargo build --release
// Start indexer
target/release/mina-indexer client account -p B62qmqMrgPshhHKLJ7DqWn1KeizEgga5MuGmWb2bXajUnyivfeMW6JE
```
Verify summary output for verbose and non-verbose JSON and summary output
```sh
target/release/mina-indexer client summary
target/release/mina-indexer client summary -v
target/release/mina-indexer client -o summary
target/release/mina-indexer client -o summary -v
```
```sh
target/release/mina-indexer client best-ledger -p /tmp
The path provided must be a file: /tmp
target/release/mina-indexer client best-ledger -p /tmp/foobar.txt
Ledger written to /tmp/foobar.txt
```
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- …
=> Cli improvements

.github/CODEOWNERS
GitHub users: @trevorbernard, @robinbb, @Isaac-Defrain will automatically be requested to review any PR against the mina-indexer project
=> Fix #226 - Add CODEOWNERS file

test
Add the ability to run individual tests.
`./test` runs all the tests
`./test test_best_canonical_tip test_indexer_cli_reports` would only run those two tests
=> Refactor regression tests to be their own functions and general improvements

src/state/ledger/account.rs, test
Solves #242, When asking for JSON from the client for an account, the client displays internal implementation details for the `PublicKey` struct. This PR overrides the serialization and deserialization of the `public_key` field on the `Account` record to use the address format, and adds a test to ensure the proper data is being returned on the client
=> Client Account Pubkey Display

src/block/parser.rs, tests/block/canonical_chain_discovery.rs
- adds a unit test for `canonical_threshold` during canonical chain discovery
Closes https://github.com/Granola-Team/mina-indexer/issues/171
=> Add canonical threshold unit test

Cargo.lock, Cargo.toml
Use the correct LTO param for the release profile and add incremental builds
Turn off LTO in the dev release
Improves: https://github.com/Granola-Team/mina-indexer/issues/248
Fixes: https://github.com/Granola-Team/mina-indexer/issues/258
=> Disable default supported features in rust-rockdb

Cargo.lock
Removes doubt about whether updating dependencies will resolve problems with the use of (transitive) unsafe/insecure dependencies. It won't the problems, it seems.
=> Update Rust package dependencies

src/bin/mainnet-test.rs, src/block/parser.rs, src/server.rs, src/state/mod.rs, tests/block/canonical_chain_discovery.rs, tests/block/parser.rs, tests/block/store/add_and_get_blocks.rs, tests/state/dangling_branches/add_all_blocks.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/317, https://github.com/Granola-Team/mina-indexer/issues/316
Remove async from function definition from `parse_file` and improve logging
=> Remove async from parse file

src/block/parser.rs
Replace `expect` with the `?` operator. This will bubble up the error to the caller rather than panicing.
Fixes: https://github.com/Granola-Team/mina-indexer/issues/339
=> Fix potential panic in BlockParser constructors

Cargo.lock, Cargo.toml, src/block/canonical_chain_discovery.rs, src/block/mod.rs, src/block/parser.rs, src/receiver/filesystem.rs, tests/receiver.rs
DONE:
- creates a separate module for canonical chain discovery
- abstracts block parsing over canonical chain discovery
- address flakiness of block receiver tests
- update `zerocopy` and `serde_yaml` deps
TODO:
- completely separate concerns
Fixes (https://github.com/Granola-Team/mina-indexer/issues/318)
=> Disentangle canonical chain discovery from block parsing

src/canonical/chain_discovery.rs, src/client.rs
- deserialize unavailable summary to `String`
Fixes https://github.com/Granola-Team/mina-indexer/issues/345
=> Client summary handling

Justfile, README.md
Clean our results directory on `just clean`
Fixes: https://github.com/Granola-Team/mina-indexer/issues/354, https://github.com/Granola-Team/mina-indexer/issues/356
=> Add Nix warning about broken versions

Justfile, src/bin/mina-indexer.rs, src/canonicity/canonical_chain_discovery.rs, src/client.rs, src/command/mod.rs, src/command/signed.rs, src/command/store.rs, src/constants.rs, src/ipc.rs, src/ledger/account.rs, src/ledger/public_key.rs, src/store.rs, test, tests/block/store/genesis.rs, tests/command/store.rs
- persist commands in an array
- embellish stored command data
- flatten transaction and ledger queries
- change `mina-indexer server cli` to `mina-indexer server start`
- add `RUST_BACKTRACE=full` to regression tests
- only build release binary when necessary
- introduce json conversion functions
Solves: https://github.com/Granola-Team/mina-indexer/issues/379 and https://github.com/Granola-Team/mina-indexer/issues/404
Starts solving: https://github.com/Granola-Team/mina-indexer/issues/342
=> Persist commands in array

Cargo.lock, Cargo.toml, tests/block/store/add_and_get_blocks.rs, tests/block/store/genesis.rs, tests/canonicity/blocks.rs, tests/canonicity/chain_discovery.rs, tests/canonicity/ledgers.rs, tests/command/store.rs, tests/event/log.rs, tests/event/replay.rs, tests/event/store.rs, tests/event/sync.rs, tests/mod.rs
- use `tempfile` temp dirs in unit tests
- remove manual resource handling
- remove `async` tests where possible
Solves https://github.com/Granola-Team/mina-indexer/issues/420
=> Unit test improvements

Justfile, ops/buildkite-pipeline.yaml, src/bin/mainnet-test.rs, src/bin/mina-indexer.rs, src/ipc.rs, src/ledger/genesis.rs, src/server.rs, src/state/mod.rs, test, tests/block/store/genesis.rs, tests/canonicity/blocks.rs, tests/canonicity/ledgers.rs, tests/command/store.rs, tests/event/log.rs, tests/event/replay.rs, tests/event/sync.rs, tests/state/ledger/genesis.rs
- introduce `GenesisLedger` for parsed genesis ledgers
- add genesis ledger, then block at startup
- add buildkite artifact
Solves https://github.com/Granola-Team/mina-indexer/issues/383
=> Parse genesis ledger only once

flake.nix, rust-toolchain.toml
Remove the explicit dependency on rust-analyzer in flake.nix in favour of using rust-toolchain.toml to manage it. So for those who do not use nix will have the same version of rust-analyzer.
=> Have rustup manage rust-analyzer

src/block/mod.rs, src/canonicity/canonical_chain_discovery.rs
Sorting all mainnet blocks previously took 13hrs and it's not down to 100ms
=> Improve canonical chain discovery block sorting

src/block/mod.rs, src/canonicity/canonical_chain_discovery.rs
Replace slower `get_state_hash` with `extract_state_hash`
=> Improve state hash extraction in canonical chain discovery

flake.lock, flake.nix
* Fixes: https://github.com/Granola-Team/mina-indexer/issues/481
=> Fix nix build issues on aarch64-darwin

.vscode/settings.json
Nix Environment Selector isn't happy in VSCode
=> Remove old mina-rs configuration from vscode settings

Justfile, rustfmt.toml
Implements Granola-Team/mina-indexer#509
Note: I did not actually run the format on the codebase (to not intermix the import changes)
=> Add rustfmt for imports_granularity = "Crate"

src/ledger/genesis.rs, tests/state/ledger/genesis.rs
Fixes
* https://github.com/Granola-Team/mina-indexer/issues/512
- Clean up genesis ledger code to remove mina-rs types
- Add back the 2 known bad genesis ledger accounts
=> Improve genesis ledger parsing

src/block/parser.rs, src/canonicity/store.rs, src/ipc.rs, src/server.rs, src/state/mod.rs, src/store.rs, tests/block/parser.rs, tests/block/store/blocks.rs, tests/block/store/blocks_at_height.rs, tests/block/store/blocks_at_slot.rs, tests/canonicity/chain_discovery.rs, tests/event/log.rs, tests/state/dangling_branches/add_all_blocks.rs, tests/state/mod.rs, tests/state/orphaned_blocks.rs
- adds `ParsedBlock` wrapper to block parser for passing orphaned block info to the witness tree
- bypasses orphaned blocks in the witness tree
- removes `best_tip` field from `IpcChannelUpdate`
- adds unit test
Fixes https://github.com/Granola-Team/mina-indexer/issues/488
Fixes https://github.com/Granola-Team/mina-indexer/issues/566
=> Orphan blocks bypass witness and use best block from store

Cargo.lock, Cargo.toml, src/receiver/filesystem.rs
This reverts commit 300e673a8f4ac0acfe4285007894c3cc714708f1 because it broke our block watching functionality.
Fixes https://github.com/Granola-Team/mina-indexer/issues/573
=> Revert "Upgrade watchexec and async-priority-channel (#552)"

src/ipc.rs, src/store.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/577
* https://github.com/Granola-Team/mina-indexer/issues/577
The IPC removes the db_path dir to remove the secondary droppings but this shouldn't happen on a primary database. Only remove non-primary stores when handling Unix Domain handle_conn calls.
=> Fix accidental deletion of the primary database by the IPCActor

Justfile
Fixes Granola-Team/mina-indexer#574
Nix environment has `rustfmt` nightly and won't work with `+nightly`. Non-Nix environment needs nightly toolchain installed and requires `+nightly`.
I ended up checking the `rustfmt` version (`stable` or `nightly`) instead of checking to see if we are inside the Nix environment. However, I'm leaving related reading about how to determine if inside a Nix environment: https://github.com/NixOS/nix/issues/6677
=> Ensure rustfmt works in all environments

rust/Cargo.lock, rust/Cargo.toml, rust/src/server.rs
Conditionally compile ingestion code to listen on filesystem events. Use inotify on linux and fsevents on macos. Inotify is more granular and likely accurate.
=> (ingestion) improve file watcher triggers

rust/src/block/mod.rs, rust/src/block/parser.rs, rust/src/canonicity/canonical_chain_discovery.rs, rust/src/server.rs, rust/src/state/mod.rs, rust/src/state/summary.rs, rust/src/store.rs, rust/src/unix_socket_server.rs, rust/test
@robinbb's addition of low-level orphaned mainnet blocks revealed two bugs:
- we were updating the `best_tip` of the witness tree incorrectly
- we were doing an invalid index check during _canonical chain discovery_
This PR
- fixes the above bugs
- adds back the removed regression tests
- reduces regression testing time to < 1min
- improves debug logging
Fixes https://github.com/Granola-Team/mina-indexer/issues/628
Fixes https://github.com/Granola-Team/mina-indexer/issues/629
Fixes https://github.com/Granola-Team/mina-indexer/issues/630
=> Fix best tip update & canonical chain discovery

ops/buildkite-pipeline.yaml
Incremental builds add unnecessary dependency-tracking and IO overhead. Not needed in CI since it's closer to building from scratch.
=> (ci) disable incremental builds in CI

Justfile, rust/Cargo.toml, rust/src/proof_systems/signer/seckey.rs, rust/src/protocol/bin_prot/polyvar/caml_hash_variant.rs, rust/src/protocol/bin_prot/value/index.rs, rust/src/protocol/bin_prot/value/layout/traverse.rs, rust/tests/mod.rs
In order to facilitate tiered testing, this PR separates the `mina-rs` unit tests from the `mina-indexer` unit tests. `mina-rs` unit tests will _not_ be run during tier 1 unit testing, i.e. `just test-unit`. They can be run via `just test-unit-mina-rs` and can later be included in a higher tier.
Fixes https://github.com/Granola-Team/mina-indexer/issues/642
=> Separate `mina-rs` unit tests

rust/src/bin/mina-indexer.rs, rust/test
- restores the indexer's ability to start from a config file
- logs config over writing to a file on startup
Fixes https://github.com/Granola-Team/mina-indexer/issues/665
Fixes https://github.com/Granola-Team/mina-indexer/issues/666
Fixes https://github.com/Granola-Team/mina-indexer/issues/675
=> Start from config file

.buildkite/hooks/pre-checkout, ops/buildkite-pipeline.yaml
Now that builds *ARE* incremental (due to presence of 'rust/target' directory), this change is merited.
=> Try incremental builds for speed

rust/test
Fixes #703 
The lack of the relatively obscure incantation 'set -o pipefail' in this script caused lines with '|' which were failing to be considered "success". This PR adds the incantation, and corrects the failing lines. Also corrected was an oversight in which 2 concurrently running tests in the same directory would use the same socket, causing both false positive tests and false negative tests, which was very confusing.
=> Correct integration tests

rust/Cargo.lock, rust/Cargo.toml, rust/src/bin/mina-indexer.rs, rust/src/client.rs, rust/src/unix_socket_server.rs, rust/test
Implements #650.
Many of these commits could (should?) be squashed. I have left them for the moment for ease of review (commit-by-commit).
=> Improvement: refine CLI commands, arguments, and communication with server documentation 

tests/regression
=> Properly kill processes (mina-indexers) in the regression test suite

flake.lock, flake.nix
Fixes: https://github.com/Granola-Team/mina-indexer/issues/722
* This was required for nix-shell integration and is not longer being used
* Remove cxxabi kludge by moving to nixos-unstable
=> (flake) remove flake-compat because it's unused

rust/src/bin/mina-indexer.rs, rust/src/server.rs, rust/src/state/mod.rs, rust/src/unix_socket_server.rs, rust/tests/canonicity/blocks.rs, rust/tests/canonicity/ledgers.rs, rust/tests/event/log.rs, rust/tests/event/memoize_ledger.rs, rust/tests/event/replay.rs, rust/tests/event/sync.rs, rust/tests/event/witness_tree.rs, rust/tests/state/orphaned_blocks.rs, tests/regression
Fixes: https://github.com/Granola-Team/mina-indexer/issues/255
Fixes: https://github.com/Granola-Team/mina-indexer/issues/726
* Add async pattern to shutdown various processes cleanly
* Remove async from the initialization function
=> Cleanly shutdown various processes in the indexer

rust/Cargo.lock, rust/src/web/graphql/stakes/mod.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/739
* Add ability to filter based on public_key
* default to epoch 0 if none is provided
* Update cargo.lock to fix cargo audit complaint
=> (stakes) add public_key query filter

rust/src/command/signed.rs, rust/src/store.rs, rust/src/web/graphql/blocks/mod.rs
This is needed as a blocker for #554.
I split this PR into multiple commits for easier review.
[move CommandStore into command/store](https://github.com/Granola-Team/mina-indexer/commit/b6230dabde23c3492db4a581fe048ff05e24b223) - This isn't strictly necessary, but seems like a good move to me. We can drop this commit if we don't want this.
=> Enhancement: store date_time in SignedCommandWithData and add functions to better store/retrieve transactions

rust/src/block/store.rs, rust/src/client.rs, rust/src/command/signed.rs, rust/src/ledger/store.rs, rust/src/store.rs, rust/src/unix_socket_server.rs, rust/tests/command/store.rs, tests/regression
This PR
- adds `get_block_children` function to `BlockStore`
- changes transaction iteration order to use global slot number
- fixes infinite wait in `test_clean_shutdown` regression test
Fixes #732
Fixes #745
=> Global slot prefix transaction keys in db

rust/src/web/graphql/transactions/mod.rs, tests/hurl/transaction.hurl
Implements Granola-Team/mina-indexer#784
Allows fetching a single transaction by transaction hash.
=>  feat: add GraphQL - transaction

rust/src/store.rs, rust/src/web/graphql/transactions/mod.rs, rust/tests/command/store.rs, tests/hurl/transactions.hurl
This attempts to fix Granola-Team/mina-indexer#785.
=> fix: fast transaction queries with limited supported sorters

rust/src/web/graphql/transactions/mod.rs
Fixes Granola-Team/mina-indexer#790
=> fix: transactions GraphQL limit handling

Justfile
also prints versions for `hurl`, `docker`, `shellcheck`
Fixes Granola-Team/mina-indexer#811
=> fix: rustfmt version determination in Just

rust/src/web/graphql/transactions/mod.rs
Fixes Granola-Team/mina-indexer#805
=> fix(GraphQL): Txn - return None (null) if proper query input is missing

rust/src/web/graphql/blocks/mod.rs, tests/hurl/blocks.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/802
* Adds transactions resolver to the block(s) GQL endpoint
* Adds fee transfer resolver to the block(s) GQL endpoint
=> Add transactions to the block GQL endpoint

rust/src/web/graphql/blocks/mod.rs, tests/hurl/blocks.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/827
* Filter out Coinbase fee transfers from the block(s) GQL endpoints
=> (gql) filter coinbase feetransfers so the UI doesn't display duplicates

rust/src/web/graphql/next_stakes/mod.rs, rust/src/web/graphql/stakes/mod.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/836
* reuse stakes GQL objects where applicable in the next stakes GQL resolver
=> (gql) reuse stakes objects where applicable in the next stakes API

rust/src/web/graphql/blocks/mod.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/846
* Use `get_blocks_at_public_key` when creator_account.public_key is in the filter
=> Use index when creator_account.public_key is in the filter

rust/src/web/graphql/mod.rs, rust/src/web/graphql/stakes/mod.rs, tests/hurl/stakes.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/849
* rename gql schema objects to work with the frontend
=> (gql) rename gql schema objects for stakes to be singular

rust/src/web/graphql/snarks/mod.rs, tests/hurl/snarks.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/857
Fixes: https://github.com/Granola-Team/mina-indexer/issues/858
* bound SNARK results to limit
* support querying and returning by state_hash that is equivalent to ME
=> Integrate snarks to fe

rust/src/ledger/staking/mod.rs, rust/src/web/graphql/next_stakes/mod.rs, rust/src/web/graphql/stakes/mod.rs, tests/hurl/stakes.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/874
* Add `% of total stake` to GQL for stakes and next stakes
=> (gql) add total stake percentage to (next)stakes endpoint

rust/src/web/graphql/snarks/mod.rs, tests/hurl/snarks.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/860
* Filter snarks by block height
=> (gql) add filter snarks by block height

rust/src/chain/store.rs, rust/src/ledger/account/mod.rs, rust/src/ledger/genesis.rs, rust/src/ledger/mod.rs, rust/src/ledger/staking/mod.rs, rust/src/state/mod.rs, rust/src/store.rs, rust/src/web/graphql/accounts/mod.rs, rust/src/web/graphql/mod.rs, rust/src/web/graphql/next_stakes/mod.rs, rust/src/web/graphql/stakes/mod.rs, rust/src/web/rest/blockchain.rs, tests/hurl/accounts.hurl, tests/regression
- subtract time-locked tokens from circulating supply (fixes #496)
- add timing info to GQL accounts (fixes #876)
=> Time locked balances

flake.nix
Solution: Use only 8 digits in tag, consistent with output of `git rev-parse --short`.
=> Problem: Nix image tag uses 9 digits (1 too many)

ops/productionize
Solution: listening to "0.0.0.0" is made explicit on production command line with this PR.
Fixes #851
=> Problem: production indexer listens only to localhost for connections

flake.nix
Corrects a failure in the "create OCI image" step due to the image label having 1 digit too few.
=> Problem: Robin can't count to 8

rust/src/web/graphql/stakes/mod.rs, tests/hurl/stakes.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/925
* Add sort_by STAKES_DESC
* Return username is None
* Remove percent symbol when returning stake weight percentage
=> (gql) remove percent symbol from total stake weight

rust/src/web/graphql/blocks/mod.rs, tests/hurl/blocks.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/928
* use `map_or` rather than `unwrap` on block height and global slot bounded queries
=> Add regression test for blocks panic

rust/src/web/graphql/feetransfers/mod.rs, tests/hurl/feetransfers.hurl
Fixes: https://github.com/Granola-Team/mina-block-explorer/issues/684
* Add filter by `blockHeight_lte` for frontend equivalence
* Improve feetransfer logic for filtering by `state_hash`
=> Add filter by `blockHeight_lte` for frontend equivalence

ops/buildkite/tier2-pipeline.yaml
Force one-at-a-time concurrency for tier-2 CI
Problem: multiple tier-2 tests, which take 15 hours to run, may run
concurrently. We want only 1 concurrent run, due to the high load.
Solution: use Buildkite's concurrency control settings.
=> Force one-at-a-time concurrency for tier-2 CI

rust/build.rs, rust/src/bin/mina-indexer.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/971
* Append git commit hash to the CLI version command
=> (cli) append git commit hash to the CLI version command

ops/tier2-test
Fixes: https://github.com/Granola-Team/mina-indexer/issues/982
* Run the ingest-all script in nix when calling tier2-testing
=> (tier2) run the ingest-all script in nix

rust/src/web/graphql/gen/mod.rs, rust/src/web/graphql/transactions/mod.rs, tests/hurl/transactions.hurl
Fixes: https://github.com/Granola-Team/mina-block-explorer/issues/684
Fix previously broken implementation
=> (gql) add filtering of transactions by blockHeight(gt(e) | lt(e))

rust/src/bin/mina-indexer.rs, rust/src/constants.rs, rust/src/web/graphql/mod.rs, rust/src/web/graphql/version/mod.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/974
* Add version GQL resolver to return the mina indexer version
=> (gql) add version resolver to return indexer version

rust/src/web/graphql/feetransfers/mod.rs, tests/hurl/feetransfers.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/987
* Fix state_hash filtering optimization
* Improve performance of the matching in the conjunction case by early exiting
=> (gql) fix incorrect filtering when state_hash and other attributes are set

rust/Cargo.lock
Fixes: https://github.com/Granola-Team/mina-indexer/issues/989
* Fix cargo audit warnings
=> (chore) fix cargo audit warnings

rust/src/web/mod.rs
Fixes Granola-Team/mina-indexer#951
=> fix(CORS): set response header `Access-Control-Allow-Origin: *`

rust/src/web/graphql/blocks/mod.rs, tests/hurl/blocks.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1003
* Fix early exit (performance issue) in the blocks GQL endpoint when the `blockHeight_lte` is set
=> (gql) fix blockHeight_lte filtering not earlying exiting for blocks

Justfile, ops/buildkite/ci-pipeline.yaml, ops/buildkite/tier2-pipeline.yaml, tests/regression, tests/stage-initial-blocks
This attempts to improve/correct the testing logic around mina-indexer shutdown. This was prompted by intermittent failures in the regression test runs (e.g. https://buildkite.com/granola/mina-indexer-tier-1/builds/1273#018fd0f6-67b7-4e68-a1b9-3ab7685273bf), which were due either to improper shutdown or (more likely) to insufficiently short 'sleep' calls (corrected in this PR to become 'wait_for_socket' invocations).
I had to make a number of refactorings in order to see what was happening in the testing. They are included in this PR.
I was successful in making the tests error out in more frequent situations if the mina-indexer is misbehaved. However, we still do not correctly shutdown in response to a SIGINT. The proof is that the socket is not deleted after the process is gone.
The …
=> Improve shutdown testing

rust/src/web/graphql/snarks/mod.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1027
* in the general case, we didn't early exit
=> (gql) fix SNARKs GQL performance regression

rust/src/web/graphql/snarks/mod.rs, tests/hurl/snarks.hurl
Fixes: https://github.com/Granola-Team/mina-block-explorer/issues/688
* Add support for filtering by blockHeight_lte for SNARKs
=> (gql) support filtering by blockHeight_lte for SNARKs GQL

rust/src/web/graphql/stakes/mod.rs, tests/hurl/stakes.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1062
* Correctly return username "Unknown" when get_username doesn't return a value
=> (gql) fix username null issue by returning unknown

rust/src/ledger/mod.rs, rust/src/web/rest/blockchain.rs, tests/data/json-schemas/summary.json
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1085
* Add total accounts to the blockchain summary REST endpoint
=> Add total accounts to the blockchain summary REST endpoint

rust/src/bin/mina-indexer.rs, tests/regression
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1010
* Rename domain-socket-path CLI argument for the server and client to socket
=> Rename domain-socket-path CLI argument to socket

rust/src/web/graphql/transactions/mod.rs, tests/hurl/transactions.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1078
* Add `state_hash` filtering to the transactions GQL endpoint
=> (gql) add filterning by block state_hash to transactions endpoint

flake.nix, ops/ingest-all, ops/productionize, rust/src/bin/mina-indexer.rs, rust/src/web/mod.rs, rust/src/web/rest/locked_balances.rs, tests/regression
Fixes: https://github.com/Granola-Team/mina-indexer/issues/920
* Include locked.csv in the binary and remove CLI configuration
=> (chore) remove locked csv from CLI and include in binary

tests/hurl/accounts.hurl, tests/hurl/feetransfers.hurl, tests/hurl/snarks.hurl, tests/hurl/transactions.hurl
Fixes Granola-Team/mina-indexer#1134
This may be overkill for some but 750 ms is still pretty fast
=> fix: increase hurl timeouts from 500 to 750

rust/Cargo.toml, rust/src/block/parser.rs, rust/src/chain/mod.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1142
* Move quickcheck to dev-dependencies
=> (test) move quickcheck to be a dev dependency

rust/src/web/graphql/accounts/mod.rs, rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/feetransfers/mod.rs, rust/src/web/graphql/snarks/mod.rs, rust/src/web/graphql/stakes/mod.rs, rust/src/web/graphql/transactions/mod.rs
Fixes Granola-Team/mina-indexer#1155
=> fix(gql): adjust Vec creation to avoid over allocation

Justfile, ops/ingest-all
Adds timings to build steps so that we can know how long they are taking, so that we can improve them.
Additionally changes our build so that it uses the Nix version of the indexer to run the Tier-2 testing. This is so that we test that version - which is the one that is intended to be eventually distributed on an OCI image.
=> Build timings

rust/src/store/snark_store_impl.rs, rust/src/web/graphql/snarks/mod.rs, tests/hurl/snarks.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1197
* Two issues, we were using an incorrect column family for our data and we were missing some SNARKs in our iteration.
=> Correct the filter by prover sort by block height GQL query

rust/src/web/graphql/snarks/mod.rs, tests/hurl/snarks.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1200
* Iterate all blocks at global slot height in prover SNARKs GQL query
=> (gql) Iterate all blocks at slot height in prover snarks GQL query

rust/src/command/mod.rs, rust/src/command/signed.rs, rust/src/ledger/account/mod.rs, rust/src/ledger/diff/account.rs, rust/src/ledger/genesis.rs, rust/src/ledger/mod.rs, rust/src/ledger/staking/mod.rs, rust/src/web/graphql/stakes/mod.rs, rust/tests/state/ledger/diff_from_precomputed.rs
Fixes Granola-Team/mina-indexer#1287
=> feat: use dedicated Nonce type Instead of u32

rust/src/bin/mina-indexer.rs, rust/src/server.rs, rust/src/unix_socket_server.rs, tests/regression.bash
Fixes Granola-Team/mina-indexer#767
The wrong PID was being captured. The PID captured was for a bash process and thus the kill signal wasn't reaching the Indexer itself.
=> fix(test): fix CLI shutdown

rust/src/web/graphql/accounts/mod.rs, tests/hurl/accounts.hurl
- resolves #1305
- adds `is_genesis_account` field to GQL accounts
=> Feat: GQL add genesis account field

rust/src/server.rs
The block and staking ledger file watcher wasn't listening on the file create event on macOS. This is the required signal when hard linking files since it never modifies the contents.
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1336
Resolves: https://github.com/Granola-Team/mina-indexer/issues/1333
=> (ingestion) fix watcher when files are hard linked for macs

rust/src/ledger/diff/account.rs
There are subtle bugs that can come from using saturating subtraction. When checking to see if the coinbase reward recipient is a new account, do explicit bounds checking to avoid underflow errors.
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1340
=> Update account creation fee logic for CoinbaseFeeTransfers: avoid saturation subtraction

rust/src/command/internal/mod.rs, rust/src/ledger/diff/account.rs, rust/src/ledger/diff/mod.rs
All account diffs are represented as an vector of all account diffs at the top level, while each inner vector represents accounts diffs that sum to zero (debits and credits). This will greatly simplify the identification of related `AccountDiff`s downstream.
Relates to (but does not close) #1352
=> Represent `AccountDiffs::from_block_fees` as a `Vec<Vec<AccountDiff>>`

rust/src/command/internal/mod.rs, rust/src/ledger/diff/account.rs, rust/src/store/version.rs, tests/hurl/accounts.hurl, tests/hurl/feetransfers.hurl, tests/hurl/stakes.hurl
* The main algorithm is now `O(n)` instead of `O(n * log(n))` 
* It is easier to read as transfers are now processed in debit/credit pairs
* For balanced pairs, runtime asserts that debits and credits sum to zero
* A duplicate was found in the feetransfers GQL for the first 120 blocks. This was fixed as a result of the rewrite.
Closes: #1352
=> Process transfers as debit/credit pairs in `InternalCommand::from_precomputed` function 

rust/src/command/internal/mod.rs, rust/src/ledger/diff/account.rs, rust/src/store/version.rs
* Reapplied the reverted PR
* Added a match statement to handle `AccountDiff::CreateAccount` (commit: https://github.com/Granola-Team/mina-indexer/commit/c28487fa37255e5a6c7e06fa8b94fb94d5232097)
Closes: #1352
=> Process transfers as debit/credit pairs in `InternalCommand::from_precomputed` function

rust/src/command/internal/mod.rs, rust/src/constants.rs, rust/src/ledger/coinbase.rs, rust/src/ledger/diff/account.rs, rust/src/ledger/diff/mod.rs, rust/src/ledger/mod.rs, rust/src/ledger/store/best.rs, rust/src/store/block_store_impl.rs, rust/src/store/version.rs, rust/tests/state/ledger/apply_diff.rs, rust/tests/state/ledger/diff_from_precomputed.rs
* Starting with `AccountDiff::from_command`, the rest of the code is refactored to support returning a list of double entries of debits and credits
* Closes #1366
=> Refactorings that move codebase closer to double entry accounting principles

rust/src/command/internal/mod.rs, rust/src/ledger/diff/account.rs, rust/src/store/version.rs
* Debits and Credits for account creation were `u64` (positive). Now they are `i64` as debits are negative, and credits are positive.
=> Ensure that debit and credit amounts are properly issued when creating accounts

rust/src/block/mod.rs, rust/src/block/parser.rs, rust/src/block/precomputed.rs, rust/src/canonicity/canonical_chain_discovery.rs, rust/src/store/version.rs
* instead of falling back to `u32::MAX` when parsing filenames for block height, we panic.
=> Confidently parse block filenames without fallbacks

.gitignore, rust/src/ledger/account/mod.rs, rust/src/ledger/mod.rs, rust/src/state/mod.rs, rust/src/store/staged_ledger_store_impl.rs, rust/src/store/version.rs, rust/src/web/graphql/accounts/mod.rs, rust/src/web/graphql/staged_ledgers/mod.rs, tests/hurl/staged_ledger_accounts.hurl
Adds a `publicKey` query input to the GQL `stagedLedgerAccounts` endpoint. This is a new feature and will allow us to further investigate our ledger diff mismatch.
=> Feat: GQL staged ledger accounts public key query input

rust/src/utility/functions.rs
* We are limited to approximately 9 billion MINA unsigned integers without causing overflow issues when converting from `u64` to `i64`. This is less that `u64::MAX`.
=> Refactor nanomina_to_mina to accept both i64 and u64

rust/src/command/mod.rs, rust/src/constants.rs, rust/src/ledger/account/mod.rs, rust/src/ledger/amount.rs, rust/src/ledger/diff/account.rs, rust/src/ledger/genesis.rs, rust/src/ledger/mod.rs, rust/src/web/rest/blockchain.rs, rust/src/web/rest/locked_balances.rs
⚠️ Depends on https://github.com/Granola-Team/mina-indexer/pull/1417
Move the `Amount` enum and traits into separate file to make future refactoring simpler
=> Move amount to new module

rust/src/ledger/coinbase.rs, rust/src/ledger/diff/account.rs, rust/src/ledger/mod.rs, rust/src/ledger/signed_amount.rs, rust/tests/state/ledger/diff_from_precomputed.rs
With a `SignedAmount` as a new field in the `PaymentDiff`, we can handle negative balances in internal commands
=> Introduce `SignedAmount` without using it yet

rust/src/block/parser.rs, rust/src/state/mod.rs, rust/src/store/version.rs, rust/tests/block/parser.rs, rust/tests/block/store/blocks.rs, rust/tests/block/store/blocks_at_height.rs, rust/tests/block/store/blocks_at_slot.rs, rust/tests/canonicity/chain_discovery.rs, rust/tests/command/store.rs, rust/tests/event/log.rs, rust/tests/state/dangling_branches/add_all_blocks.rs
* Block iteration and block parsing are currently entwined concepts.
* Currently, each iteration of the block paths results in parsing the file contents into a `PrecomputedBlock`. 
* This means that entire JSON of each block is serialized into memory upon each iteration, making ingestion slow. 
* In the future, we may want to avoid serializing the entire file into memory when ingesting. This helps.
=> Separate block iteration from block parsing

rust/src/block/mod.rs, rust/src/canonicity/canonical_chain_discovery.rs, rust/src/store/version.rs
Allocates memory on the stack (not the heap) when parsing height and state hash from fn.
=> Use memory on stack when extracting height and state hash from filename

rust/src/canonicity/canonical_chain_discovery.rs, rust/src/store/version.rs
⚠️ depends on https://github.com/Granola-Team/mina-indexer/pull/1439
Avoids heap allocations by using &str in the parent_hash_map
=> Allocate memory on the stack for `parent_hash_map` hashes in `discovery` algorithm

rust/src/ledger/store/staged.rs, rust/src/store/version.rs
Allocates memory in stack, instead of heap.
=> Use array not Vec for `staged_account_key`

rust/src/block/mod.rs, rust/src/ledger/store/staged.rs, rust/src/store/block_store_impl.rs, rust/src/store/mod.rs, rust/src/store/staged_ledger_store_impl.rs, rust/src/store/staking_ledger_store_impl.rs, rust/src/store/version.rs
* Makes a step towards better memory utilization. 
* Follow up issue has been created to convert other functions to &[u8] : https://github.com/Granola-Team/mina-indexer/issues/1442
=> `BlockHash::to_bytes -> [u8; BlockHash::LEN]` instead of `... -> Vec<u8>`

rust/src/ledger/public_key.rs, rust/src/ledger/store/staged.rs, rust/src/store/best_ledger_store_impl.rs, rust/src/store/block_store_impl.rs, rust/src/store/mod.rs, rust/src/store/staking_ledger_store_impl.rs, rust/src/store/username_store_impl.rs
⚠️ depends on https://github.com/Granola-Team/mina-indexer/pull/1443
* A step towards better memory utilization. 
* Other functions need to be updated and they are being tracked in https://github.com/Granola-Team/mina-indexer/issues/1442
=> `PublicKey::to_bytes() -> [u8; PublicKey:LEN]` instead of `... -> Vec<u8>`

rust/src/store/snark_store_impl.rs, rust/src/store/version.rs
=> Refactor `snark_fee_prefix_key` to return `[u8, ...]` instead of `Vec<u8>`

rust/src/store/internal_command_store_impl.rs, rust/src/store/version.rs
Since we work with bytes in rocksdb, we should also be more precise in how we retrieve the bytes by avoiding vectors
=> Avoid unnecessary vec allocations

rust/src/server.rs, rust/src/state/mod.rs, rust/src/store/mod.rs, rust/src/store/version.rs
I have noticed the build pipeline starts by predicting a finishing time that gradually increases until about 80000 blocks, where it stabilizes and becomes more accurate. I wonder if compaction every 50000 blocks might help.
=> Manual compaction every 50000 blocks

rust/src/web/graphql/mod.rs, rust/src/web/graphql/transactions/mod.rs
=> fix: Use millis over internal string for ordering GQL date time

rust/src/canonicity/canonical_chain_discovery.rs, rust/src/store/version.rs
* Build a map of previous state hashes using threads to avoid blocking I/O on single thread.
* Benchmark on `40k` blocks yield `0s` discovery vs `19s` on main.
* Given that this is a 10 minute process in tier3, this should yield savings.
=> Make canonical discovery algorithm near instantaneous

rust/src/web/graphql/top_snarkers.rs, tests/hurl/top_snarkers.hurl
Returns username `"Unknown"` instead of `null`.
- #1558
=> fix(gql): use Unknown username for top snarkers

rust/src/store/snark_store_impl.rs, rust/src/store/version.rs, tests/regression.bash
Corrects the epoch SNARK fee values stored in the db and used by GQL.
- #1565
=> fix(gql): correct epoch SNARK fees

rust/src/state/mod.rs, rust/tests/event/sync.rs
Fixes a duplication of the witness tree's root block on sync.
- #1594
=> fix(state): dedupe witness tree root block

docs/user-commands.md, rust/src/block/precomputed.rs, rust/src/command/mod.rs, rust/src/command/signed/mod.rs, rust/src/command/zkapp.rs, rust/src/ledger/account/mod.rs, rust/src/ledger/diff/account.rs, rust/src/ledger/diff/mod.rs, rust/src/ledger/mod.rs, rust/src/protocol/serialization_types/staged_ledger_diff.rs, rust/src/store/best_ledger_store_impl.rs, rust/src/web/graphql/transactions/mod.rs, rust/tests/state/ledger/diff_from_precomputed.rs
- adds V2 `Signed_command` type
- implements user & signed command functions
- uses borrows over ownership
- #1620
- #1655
=> feat(berkeley): add user command types

rust/src/web/graphql/blocks/mod.rs
Refactor to minimize duplicate code.
=> chore(web): refactor blocks GraphQL

rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/mod.rs, rust/src/web/graphql/transactions/mod.rs, rust/src/web/mod.rs, rust/src/web/rest/blocks.rs, tests/regression.bash
If you step through at the commit level, it will be much easier to follow.
Return the full block (see example below)
Make height a query variable
Remove query by slot (unnecessary)
```json
[
{
"canonical": true,
"epoch_num_blocks": 166,
"epoch_num_canonical_blocks": 100,
"epoch_num_supercharged_blocks": 20,
"total_num_blocks": 166,
"total_num_canonical_blocks": 100,
"total_num_supercharged_blocks": 20,
"block_num_snarks": 0,
"block_num_user_commands": 3,
"block_num_internal_commands": 2,
"epoch_num_slots_produced": 100,
"num_unique_block_producers_last_n_blocks": null,
"block": {
"state_hash": "3NKGnZMYQiKAZDZfAnyHgVPhSrMWRHaR3aHMnAc28oatHJiifVFz",
"block_height": 95,
"global_slot_since_genesis": 136,
"winner_account": {
"public_key": …
```
=> feat(web)!: return full block in blocks REST endpoint

rust/src/block/mod.rs, rust/src/block/post_hardfork/account_accessed.rs, rust/src/block/post_hardfork/account_created.rs, rust/src/block/post_hardfork/mod.rs, rust/src/block/post_hardfork/token_used.rs, rust/src/block/precomputed.rs, rust/src/constants.rs, rust/src/ledger/account/mod.rs, rust/src/ledger/amount.rs, rust/src/ledger/genesis.rs, rust/src/ledger/staking/mod.rs, rust/src/ledger/staking/permissions.rs, rust/src/ledger/token/symbol.rs, rust/src/mina_blocks/v2/mod.rs, rust/src/mina_blocks/v2/staged_ledger_diff/mod.rs, rust/src/store/version.rs, rust/src/web/graphql/accounts/mod.rs
- refactors/separates staking/account permissions
- fixes v2 block deserialization
- includes v2 block data in PCB
=> feat(zkapp): continue zkapp ledger diff prep

rust/src/command/signed/mod.rs
- uses the corrected mina daemon zkapp parsing code
- removes stubbed out zkapp command hashes
- #1699
- https://github.com/Granola-Team/mina/commit/f641e5bf06e77186db65292fa747842b4fa43f95
=> fix(signed): use the corrected mina daemon zkapp parser
