src/bin/mina-indexer-server.rs
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204406714391518
=> System exit when failed genesis parsing

src/bin/mina-indexer.rs, src/server/mod.rs
Adding sane defaults for CLI flags.
=> Sane defaults for CLI flags

Cargo.toml, src/bin/mainnet-test.rs, src/block/store.rs, src/server/mod.rs
A lil app to ingest mainnet blocks and measure metrics
=> Block ingestion app

src/bin/mainnet-test.rs, src/block/parser.rs, src/server/mod.rs
- improves the options and metrics for block ingestion app
- fixes the presorting comparison
=> Block ingestion app round 2

src/bin/mainnet-test.rs, src/block/mod.rs, src/block/receiver.rs, src/server/mod.rs
Adds a "cron job" to download next blocks to the watch directory after initial ingestion
=> Ingestion app watch cron job

src/state/ledger/diff/account.rs, src/state/ledger/mod.rs
Tests and error handling! So far within the ledger directory. Refactor the mod.rs slightly with error handling. Also fixes the clippy warning.
=> Tests and error handling

src/block/mod.rs, src/block/parser.rs, src/block/precomputed.rs, src/state/ledger/coinbase.rs, src/state/ledger/command.rs, src/state/ledger/diff/account.rs, src/state/ledger/diff/mod.rs, src/state/mod.rs
- fixes the bug in the canonical chain discovery algorithm
- simplifies command accessor functions and makes corresponding changes throughout
=> Fix canonical chain discovery bug

src/block/parser.rs
- fixes a bug caused by early gaps in the tree of startup blocks
=> Fully account for gaps during canonical chain discovery

src/block/parser.rs
- fixes length comparison bug in block parser
=> Fix length comparison bug

src/server/mod.rs
To test ensure the `mina-indexer.sock` exists and turn on debug logging.
=> Clean up old domain socket from previous invocation

src/bin/staking-ledger-ingestion.rs, src/block/parser.rs, src/gql/schema/stakes.rs, src/lib.rs, src/state/mod.rs, src/state/summary.rs
Testing ingestion showed me that our time reporting could be improved. This PR
- improves how we report time in logs and summary
(Follows https://github.com/Granola-Team/mina-indexer/pull/150)
=> Time reporting

src/bin/staking-ledger-ingestion.rs, src/block/parser.rs, src/gql/schema/stakes.rs
- remove `println!()` from block parser
- appease clippy
=> Clean up various files

src/bin/mainnet-test.rs, src/lib.rs
Simple correction of my arithmetic operational dyslexia
=> Fix time display calculations

src/bin/mainnet-test.rs
Deletes an existing test db for `mainnet-test`
=> Delete and refresh db before ingestion

Cargo.lock, Cargo.toml, src/server.rs
Adds the ability to exit the server process via ctrl-c at any point
=> Ctrlc server

src/bin/mina-indexer.rs
This reverts commit c3e7792b0998cc0d8f45a1bd5a893c8489d5b742.
=> Revert "(ux) Delete existing RocksDB dir"

README.md
Quick start guide for the indexer. Concise, to the point.
=> Quick start guide

src/bin/mainnet-test.rs, src/block/mod.rs, src/block/precomputed.rs, src/client.rs, src/receiver/google_cloud/worker.rs, src/state/branch.rs, src/state/mod.rs, tests/block/canonical_chain_discovery.rs, tests/state/dangling_branches/add_all_blocks.rs
Remove Option from `blockchain_length` field by reading into parsed block if length not in filename
* https://app.asana.com/0/1203669416123378/1205397157281886/f
=> Blockchain length option

README.md
The Collective Code Contribution Contract is an evolution of the GitHub Fork and Pull model. C4 is meant to provide a reusable optimal collaboration model for open source software projects.
=> Fix #206 - Add code contribution policy

src/bin/mina-indexer.rs, src/client.rs, src/server.rs, src/state/mod.rs
There are no tests to determine if this feature is working
=> Problem: Save snapshot not adequately tested

download_blocks, flake.nix, src/server.rs, test
Changes the server IPC listener to open before the server initialization, so the client can communicate with the server during initialization. Also adds a test to verify this functionality. Related: #225, #221
=> Open IPC Sooner

Justfile, flake.nix
* Fix https://github.com/Granola-Team/mina-indexer/issues/232 - Add support for Just
=> Add just support

.github/workflows/ci.yaml, src/lib.rs, src/server.rs, test
Fix https://github.com/Granola-Team/mina-indexer/issues/229 - Use Just in the CI/CD Pipeline to trigger the regression suite
=> Use just in the CI/CD pipeline

src/server.rs
Addressing `Problem: the indexer server isn't correctly initialized if the startup-blocks directory doesn't exist #225` https://github.com/Granola-Team/mina-indexer/issues/225
=> Addressing issue #225

src/bin/mina-indexer.rs, src/ipc.rs, src/lib.rs, src/server.rs, test
This pull request fixes the inconsistencies with running the regression test suite locally, as well as some QoL changes regarding removing dangling socket files, etc.
Closes #252, #251
=> Fix Test Bugs

test
=> Use temporary directories for logs, database

README.md
Fixes: https://github.com/Granola-Team/mina-indexer/issues/276
=> Change to use the buildkite build badge

flake.nix
Fixes: https://github.com/Granola-Team/mina-indexer/issues/274
=> Remove the remote update command to submodules

Cargo.lock, Cargo.toml, Justfile, flake.nix, ops/shell.nix
Fixes: https://github.com/Granola-Team/mina-indexer/issues/275
=> Disallow unused cargo deps

src/block/parser.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/281
The block parser was written to consume PrecomputedBlocks from a flat directory or a nested one. The latter was never used and remained untested. This PR removes it.
=> Remove unsupported BlockParser mode of operation

src/store.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/301
=> Remove canonicity cf

flake.nix, ops/buildkite-pipeline.yaml
=> Delete extraneous Nix shell

README.md
Fixes: https://github.com/Granola-Team/mina-indexer/issues/196
Rewrite the README to reflect reality
=> Update README to reflect reality

ops/buildkite-pipeline.yaml
=> Decrease build pipeline steps

src/bin/mina-indexer.rs, src/server.rs, test
Fixes: https://github.com/Granola-Team/mina-indexer/issues/311
=> Replace `create_dir_if_non_existence` with `std::fs::create_dir_all`

README.md
Address comment from previous PR
=> Address wording ambiguity from previous README PR

src/block/mod.rs, src/block/parser.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/319
=> Add asserts to unit test

src/block/signed_command.rs, src/state/ledger/mod.rs, src/state/ledger/post_balances.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/328
=> Change nonce to u32

src/bin/mina-indexer.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/331
=> Move logger initialization into it's own function

src/bin/mina-indexer.rs, src/server.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/333
=> Remove MinaIndexerRunPhase

Cargo.lock, Cargo.toml, src/block/mod.rs, src/block/parser.rs, src/state/mod.rs, test
- add property-based testing for block file names
Fixes https://github.com/Granola-Team/mina-indexer/issues/323
=> Improve file name validation

src/bin/mina-indexer.rs, src/client.rs, src/server.rs, src/state/mod.rs, test
- flatten client subcommands
- update regression tests
- remove unused code
Fixes https://github.com/Granola-Team/mina-indexer/issues/284 and https://github.com/Granola-Team/mina-indexer/issues/285
=> Cli improvements

src/bin/mainnet-test.rs, src/block/mod.rs, src/ipc.rs, src/receiver/filesystem.rs, src/server.rs, src/state/branch.rs, src/state/mod.rs, src/store.rs, test, tests/canonical/blocks.rs, tests/canonical/ledgers.rs, tests/event/log.rs, tests/event/replay.rs, tests/event/sync.rs
DONE:
- add sync and replay server initialization
- add sync and replay regression tests
TODO:
- add genesis block to block store
- handle watcher events
Fixes https://github.com/Granola-Team/mina-indexer/issues/353
=> Sync and replay regression tests

src/block/blockchain_length.rs, src/block/precomputed.rs, src/block/previous_state_hash.rs, src/client.rs, src/command/mod.rs, src/command/signed.rs, src/command/store.rs, src/ipc.rs, src/ledger/diff/mod.rs, src/store.rs, test, tests/command/store.rs
- add state hash bounds for chain queries
- add state hash bounds for transaction queries
- store commands with state hash
Fixes https://github.com/Granola-Team/mina-indexer/issues/363
=> State hash bounds for transaction and chain queries

src/bin/mainnet-test.rs, src/bin/mina-indexer.rs, src/block/precomputed.rs, src/canonicity/canonical_chain_discovery.rs, src/client.rs, src/command/mod.rs, src/constants.rs, src/ledger/account.rs, src/lib.rs, src/server.rs, src/state/branch.rs, src/state/mod.rs, tests/block/store/add_and_get_blocks.rs, tests/block/store/genesis.rs, tests/canonicity/blocks.rs, tests/canonicity/chain_discovery.rs, tests/canonicity/ledgers.rs, tests/command/store.rs, tests/event/log.rs, tests/event/replay.rs, tests/event/sync.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/372
=> Refactor constants out of src/lib.rs into its own file

src/client.rs, src/ipc.rs, src/store.rs, test
- add rocksdb checkpointing for indexer store
- add client checkpoint command
- add ipc checkpoint handling
- add checkpoint regression tests
Fixes https://github.com/Granola-Team/mina-indexer/issues/377
=> Indexer store checkpoint

Justfile
=> Undo unit-test hack

Justfile, flake.nix, test
=> Store PID of mina-indexer server and kill correct process when tests complete

Cargo.toml, Justfile, tests/receiver.rs
=> Use release profile and omit unnecessary check

Cargo.lock, Cargo.toml, src/server.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/439
=> Remove query receiver pattern

Cargo.lock, Cargo.toml, src/server.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/441
=> Remove ctrlc dep

src/block/mod.rs, src/client.rs, src/command/mod.rs, src/command/signed.rs, src/ipc.rs, src/ledger/account/mod.rs, src/ledger/account/ser_de.rs, src/ledger/mod.rs, src/receiver/filesystem.rs, src/server.rs, src/snark_work/mod.rs, src/state/mod.rs, src/store.rs, test
- fix transaction queries (https://github.com/Granola-Team/mina-indexer/issues/451)
- fix ledger queries (https://github.com/Granola-Team/mina-indexer/issues/452)
- add basic block queries (https://github.com/Granola-Team/mina-indexer/issues/449)
- add basic block query regression test (https://github.com/Granola-Team/mina-indexer/issues/453)
- remove unused `--json` args (https://github.com/Granola-Team/mina-indexer/issues/450)
- fix fs receiver (https://github.com/Granola-Team/mina-indexer/issues/454)
=> Fix queries and clean up ipc

src/block/mod.rs, src/block/precomputed.rs, src/canonicity/mod.rs, src/canonicity/store.rs, src/ipc.rs, src/state/mod.rs, src/store.rs, test
- add canonicity data to block query results (https://github.com/Granola-Team/mina-indexer/issues/461)
=> Block canonicity

src/block/parser.rs, src/block/store.rs, src/event/db.rs, src/event/witness_tree.rs, src/ipc.rs, src/server.rs, src/state/mod.rs, src/store.rs, test, tests/event/log.rs, tests/event/mod.rs, tests/event/store.rs, tests/event/witness_tree.rs, tests/state/dangling_branches/complex/basic.rs, tests/state/dangling_branches/complex/multiple_branches.rs, tests/state/dangling_branches/complex/multiple_gaps.rs, tests/state/dangling_branches/simple/improper_forward.rs
- add best block to `IndexerStore`
- add witness tree event `UpdateBestTip` and pass to `IndexerStore` in the block pipeline
- handle best block updates
- fix canonical threshold handling
- add canonical threshold regression test
Fixes: https://github.com/Granola-Team/mina-indexer/issues/463, https://github.com/Granola-Team/mina-indexer/issues/464
=> Add best block to store

.gitignore, Cargo.lock, Cargo.toml, Dockerfile, flake.lock, flake.nix, rust-toolchain.toml, src/bin/mina-indexer.rs, src/block/precomputed.rs, src/command/mod.rs, src/lib.rs, src/store.rs, src/web/mod.rs, src/web/rest/blocks.rs, src/web/rest/mod.rs, tests/state/dangling_branches/complex/basic.rs, tests/state/dangling_branches/complex/multiple_gaps.rs, tests/state/dangling_branches/simple/basic_multiple_branch.rs, tests/state/dangling_branches/simple/multiple_branch.rs, tests/state/dangling_branches/simple/proper_forward.rs, tests/state/dangling_branches/simple/reverse.rs
Fixes:
* Add Webserver (https://github.com/Granola-Team/mina-indexer/issues/375)
* add get block REST API (https://github.com/Granola-Team/mina-indexer/issues/368)
=> Add get block REST API

src/block/mod.rs, src/block/parser.rs, src/block/precomputed.rs, src/block/store.rs, src/client.rs, src/ipc.rs, src/state/mod.rs, src/store.rs, test, tests/block/store/blocks.rs, tests/block/store/blocks_at_height.rs, tests/block/store/blocks_at_slot.rs, tests/block/store/mod.rs
- add height and slot block indices
- add queries and handling
- sort block in query response
Fixes https://github.com/Granola-Team/mina-indexer/issues/469
Fixes https://github.com/Granola-Team/mina-indexer/issues/470
=> Height and slot block indices

src/bin/mina-indexer.rs, test
Fixes https://github.com/Granola-Team/mina-indexer/issues/472
=> Record server args on startup

flake.nix, src/bin/mina-indexer.rs, src/web/mod.rs, src/web/rest/accounts.rs, src/web/rest/mod.rs, test
Fixes: 
* https://github.com/Granola-Team/mina-indexer/issues/369
* https://github.com/Granola-Team/mina-indexer/issues/490
=> Add `accounts/{public_key}` REST endpoint for best ledger

Cargo.lock, Cargo.toml, src/web/mod.rs, src/web/rest/blockchain.rs, src/web/rest/mod.rs
Currently missing offline locked tokens.
=> (rest) Add blockchain summary endpoint

Cargo.lock, Cargo.toml, flake.nix, src/bin/mina-indexer.rs, src/ledger/account/mod.rs, src/web/mod.rs, src/web/rest/blockchain.rs, src/web/rest/locked_balances.rs, src/web/rest/mod.rs, test, tests/json-schemas/summary.json
Fixes:
* https://github.com/Granola-Team/mina-indexer/issues/497
=> Incorporate locked supply into blockchain summary endpoint

src/server.rs
Fixes:
* https://github.com/Granola-Team/mina-indexer/issues/478
=> Improve error handling on startup

src/ledger/account/mod.rs, src/ledger/coinbase.rs, src/ledger/genesis.rs, src/ledger/mod.rs
Fixes
* https://github.com/Granola-Team/mina-indexer/issues/518
=> Account delegates must not be empty

LICENSE, README.md
Fixes #522.
**Do not squash.**
=> Use Apache 2.0 license instead of MPLv2 

src/block/genesis.rs, src/ledger/account/mod.rs, src/ledger/genesis.rs, test, tests/state/ledger/genesis.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/504
* https://github.com/Granola-Team/mina-indexer/issues/504
=> Add genesis block winner to genesis ledger

src/command/mod.rs, src/ledger/account/mod.rs, src/ledger/diff/account.rs, src/ledger/diff/mod.rs, src/ledger/mod.rs, test, tests/state/ledger/apply_diff.rs, tests/state/ledger/diff_from_precomputed.rs
- handle failed transaction nonces
- add nonce regression test
Fixes https://github.com/Granola-Team/mina-indexer/issues/564
=> Fix failed transaction nonces

test
Fixes: https://github.com/Granola-Team/mina-indexer/issues/570
* https://github.com/Granola-Team/mina-indexer/issues/570
=> Choose random port for http tests in regression suite

src/state/mod.rs, test
Fixes: https://github.com/Granola-Team/mina-indexer/issues/579
* https://github.com/Granola-Team/mina-indexer/issues/579
=> improve logging when adding orphaned and deep canonical blocks to the store

Dockerfile, rust-toolchain.toml, src/block/parser.rs
=> feat: upgrade Rust from 1.75 to 1.76

src/block/parser.rs, src/block/precomputed.rs, src/ipc.rs, src/state/mod.rs
Closes Granola-Team/mina-indexer#582
Docs: https://docs.rs/anyhow/latest/anyhow/macro.bail.html
Preferred positional formatting argument instead of string interpolation.
=> Use bail!(...) instead of Err(anyhow!(...))

.github/dependabot.yml, test
=> Reduce dependabot frequency to monthly

test
Fixes https://github.com/Granola-Team/mina-indexer/issues/591
=> Add watch staking ledgers regression test

Justfile
Fixes: https://github.com/Granola-Team/mina-indexer/issues/623
=> Add json-checkschema to just prereqs

flake.nix, shell.nix
Fixes: https://github.com/Granola-Team/mina-indexer/issues/631
=> (nix) format nix files with nixfmt

rust/test
Fixes: https://github.com/Granola-Team/mina-indexer/issues/635
=> (tests) wait for socket instead of sleep

rust/Cargo.lock, rust/Cargo.toml, rust/src/server.rs, rust/src/state/branch.rs, rust/src/store.rs, rust/test
Fixes https://github.com/Granola-Team/mina-indexer/issues/403
Fixes https://github.com/Granola-Team/mina-indexer/issues/640
=> Remove unused serde deps

ops/ingest-all, rust/download_blocks, rust/src/bin/mina-indexer.rs, rust/src/canonicity/canonical_chain_discovery.rs, rust/src/server.rs, rust/src/state/mod.rs, rust/test
=> Improve command line for server

ops/ingest-all, ops/upload-all, ops/upload-to-bucket
=> Add more ops files

rust/src/ledger/store.rs, rust/src/server.rs, rust/src/state/mod.rs, rust/src/store.rs, rust/src/unix_socket_server.rs, rust/src/web/rest/accounts.rs, rust/src/web/rest/blockchain.rs, rust/tests/canonicity/ledgers.rs, rust/tests/event/memoize_ledger.rs, rust/tests/event/mod.rs
Fixes https://github.com/Granola-Team/mina-indexer/issues/656
Fixes https://github.com/Granola-Team/mina-indexer/issues/658
=> Memoize staged ledgers on query only

rust/src/client.rs, rust/src/command/internal.rs, rust/src/command/signed.rs, rust/src/command/store.rs, rust/src/constants.rs, rust/src/ledger/coinbase.rs, rust/src/ledger/diff/account.rs, rust/src/state/mod.rs, rust/src/store.rs, rust/src/unix_socket_server.rs, rust/test, rust/tests/command/store.rs
- indexes internal commands by public key and state hash
Fixes https://github.com/Granola-Team/mina-indexer/issues/654
=> Store internal commands

rust/src/bin/mina-indexer.rs, rust/src/client.rs, rust/src/constants.rs, rust/src/server.rs, rust/src/unix_socket_server.rs, rust/test
Implements Granola-Team/mina-indexer#670.
Also part of #650.
=> feat: add CLI option for Unix domain socket path and organize shutdown

ops/buildkite-pipeline.yaml
Fixes: https://github.com/Granola-Team/mina-indexer/issues/673
=> Fix issue 673

rust/src/ledger/staking/mod.rs, rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/mod.rs, rust/src/web/graphql/stakes/mod.rs, rust/src/web/mod.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/557
=> Add stakes GQL endpoint

flake.nix, ops/buildkite-pipeline.yaml, rust/test
=> Productionize the Nix build

rust/src/bin/mina-indexer.rs, rust/src/server.rs, rust/test
Fixes https://github.com/Granola-Team/mina-indexer/issues/646
=> Startup without blocks dir

ops/buildkite-pipeline.yaml
=> Run expensive build step only on main branch

Justfile, ops/buildkite-pipeline.yaml
=> Clarify 'test-ci' vs 'test' Justfile targets

tests/regression
=> Use --web-port on invocations of server

rust/src/client.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/716
=> Fill in empty CLI arg docs

rust/src/unix_socket_server.rs
Fixes Granola-Team/mina-indexer#725
=> fix: if path is supplied to transactions state-hash CLI, write to path

rust/src/store.rs
=> Aggregate staking delegations on ingestion

rust/src/bin/mina-indexer.rs, rust/src/server.rs, tests/regression
=> Initialize without staking ledgers

rust/src/web/graphql/stakes/mod.rs, rust/src/web/mod.rs
add compression middleware to the webserver
=> (stakes) use pre-calculated delegation totals

rust/src/web/graphql/mod.rs, rust/src/web/graphql/stakes/mod.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/737
=> (stakes) add limit and sortBy options required by the frontend

ops/start-server, rust/Cargo.lock, rust/Cargo.toml, rust/src/bin/mina-indexer.rs, rust/src/block/parser.rs, rust/src/canonicity/canonical_chain_discovery.rs, rust/src/client.rs, rust/src/command/mod.rs, rust/src/ledger/mod.rs, rust/src/server.rs, rust/src/state/branch.rs, rust/src/state/mod.rs, rust/src/store.rs, rust/src/unix_socket_server.rs, rust/src/web/mod.rs, rust/src/web/rest/accounts.rs, rust/src/web/rest/blockchain.rs, tests/regression
=> Improve logging

ops/buildkite-pipeline.yaml, ops/ingest-all, rust/src/bin/mina-indexer.rs, tests/regression, tests/stage-blocks, tests/stage-initial-blocks
=> Add Tier 2 Testing

rust/src/block/store.rs, rust/src/store.rs, rust/src/web/graphql/accounts/mod.rs, rust/src/web/graphql/mod.rs, tests/regression
Fixes: https://github.com/Granola-Team/mina-indexer/issues/747
* Add accounts GQL endpoint
=> (gql) add accounts endpoint

Justfile, flake.nix, tests/regression, tests/stage-blocks, tests/stage-initial-blocks
Fixes #759 
Fixes #760 
Fixes #762
=> Improve PID and retry logic

tests/regression
=> Use better logic for checking for a killed process

tests/regression
=> Comment out test_clean_shutdown

rust/src/bin/mina-indexer.rs, rust/src/server.rs, tests/regression
=> Missing block recovery

tests/recovery.sh, tests/regression
=> Do not require a writable  directory

ops/buildkite-pipeline.yaml
=> Work around bug in Buildkite logic; run nix nightly

rust/src/bin/mina-indexer.rs, rust/src/server.rs, rust/src/state/mod.rs, tests/recovery.sh, tests/regression
=> Missing block recovery improvement & fix best block selection

rust/src/server.rs, rust/src/state/mod.rs, rust/src/state/summary.rs, tests/regression
=> Fix blocks processed and include staking ledger info in summary

tests/regression
Resolves Granola-Team/mina-indexer#778
=> chore: dedupe regression test server start code

rust/src/state/mod.rs, rust/src/store.rs, rust/src/web/graphql/feetransfers/mod.rs
Use Isaac's bigendian sorting method to support sorting by block height
=> Feetransfer improvements

rust/src/store.rs, rust/src/web/graphql/blocks/mod.rs, tests/hurl/blocks.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/694
=> (gql) add blocks GQL endpoint

rust/src/client.rs, rust/src/snark_work/mod.rs, rust/src/snark_work/store.rs, rust/src/store.rs, rust/src/unix_socket_server.rs, tests/regression
=> Top snark producers

tests/hurl/accounts.hurl, tests/hurl/stakes.hurl, tests/regression
=> Add additional hurl tests

rust/src/web/graphql/transactions/mod.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/807
Fixes: https://github.com/Granola-Team/mina-indexer/issues/806
* correct transaction memo decoding
* convert nanomina to f64 using decimals
=> (gql) correct decoding memos and use decimal for mina conversion

rust/src/web/graphql/accounts/mod.rs, rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/feetransfers/mod.rs, rust/src/web/graphql/snarks/mod.rs, rust/src/web/graphql/stakes/mod.rs, rust/src/web/graphql/transactions/mod.rs, tests/hurl/transactions.hurl
Use the db helper methods to retrieve the DB from the context
=> Use default values for QueryInputs

rust/src/web/graphql/stakes/mod.rs, tests/hurl/stakes.hurl
Fixes/Implements Granola-Team/mina-indexer#751
=> feat(GraphQL): add timing to Stakes query

rust/src/web/graphql/blocks/mod.rs, tests/hurl/blocks.hurl
Works with the a modified frontend
=> (gql) modify blocks GQL schema to work with the frontend

rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/feetransfers/mod.rs, rust/src/web/graphql/mod.rs, rust/src/web/graphql/transactions/mod.rs
=> Improvement(GraphQL): clean up Blocks/Transactions

rust/src/web/graphql/mod.rs, rust/src/web/graphql/next_stakes/mod.rs, tests/hurl/next_stakes.hurl, tests/hurl/stakes.hurl
=> Add GQL next stakes

rust/src/web/graphql/next_stakes/mod.rs, tests/hurl/next_stakes.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/834
* modify our nextStakes resolver to conform to MinaExplorer's API
=> (gql) make nextStakes resolver conform to mina explorer's API

rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/gen/mod.rs, tests/hurl/blocks.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/842
Fixes: https://github.com/Granola-Team/mina-indexer/issues/843
Fixes: https://github.com/Granola-Team/mina-indexer/issues/845
* Change to use block_height instead of blockchain_length for compatibility
* Query by slot
* Change to camelCase for publicKeys when filtering on creator account
=> Update gql for blocks to support the new columnar features in the frontend

rust/src/block/mod.rs, rust/src/ledger/account/mod.rs, rust/src/ledger/genesis.rs, rust/src/ledger/mod.rs, rust/src/ledger/staking/mod.rs, rust/src/mina_blocks/v2/mod.rs, rust/src/mina_blocks/v2/precomputed_block.rs, rust/src/mina_blocks/v2/protocol_state/mod.rs, rust/src/mina_blocks/v2/staged_ledger_diff/command.rs, rust/src/mina_blocks/v2/staged_ledger_diff/mod.rs, rust/src/web/graphql/accounts/mod.rs, rust/src/web/graphql/stakes/mod.rs, rust/tests/data/berkeley/non_sequnetial_blocks/berkeley-4969-3NL8QoLQMtsBH8vUnccQw3vt8PgYuZRMApq1yZT1jwhZjbBLMRJU.json
Fixes #748
Fixes #867
Zkapps required the timing info anyways so I added both in this PR
=> Improve zkapps parsing & add timing to ledger `Account`

rust/src/web/graphql/snarks/mod.rs, tests/hurl/snarks.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/861
* Add filtering snarks by state hash
=> (gql) add filtering snarks by state hash

rust/src/web/graphql/feetransfers/mod.rs, tests/hurl/feetransfers.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/862
* Filter by recipient in feetransfers
=> (gql) feetransfers filter by recipient

rust/src/bin/mina-indexer.rs, rust/src/block/precomputed.rs, rust/src/client.rs, rust/src/event/db.rs, rust/src/event/ledger.rs, rust/src/ledger/staking/mod.rs, rust/src/ledger/staking/parser.rs, rust/src/ledger/store.rs, rust/src/server.rs, rust/src/state/mod.rs, rust/src/store.rs, rust/src/unix_socket_server.rs, rust/src/web/graphql/accounts/mod.rs, rust/src/web/graphql/next_stakes/mod.rs, rust/src/web/graphql/stakes/mod.rs, rust/src/web/rest/accounts.rs, rust/src/web/rest/blockchain.rs, rust/tests/canonicity/ledgers.rs, rust/tests/event/memoize_ledger.rs, rust/tests/event/store.rs, rust/tests/event/witness_tree.rs, tests/regression
=> Use genesis state hash over network name for storing staking ledgers & delegation calculations

rust/src/web/rest/blockchain.rs
=> (rest) change log-level to trace

flake.nix, ops/build-oci-image, ops/buildkite-pipeline.yaml
Corrected yesterday's correction related to number of hex digits in the OCI image's tag. Made it easier to test the CI build step independently.
=> Correct OCI image build

rust/src/web/graphql/feetransfers/mod.rs, tests/hurl/feetransfers.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/923
* Correct schema to handle query from the frontend
=> (gql) add filtering by state_hash for feetransfers

rust/src/block/precomputed.rs, rust/src/block/store.rs, rust/src/store/column_families.rs, rust/src/store/fixed_keys.rs, rust/src/store/mod.rs, rust/src/web/graphql/accounts/mod.rs, rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/feetransfers/mod.rs, rust/src/web/graphql/next_stakes/mod.rs, rust/src/web/graphql/stakes/mod.rs, rust/src/web/rest/blockchain.rs, tests/data/json-schemas/summary.json, tests/hurl/accounts.hurl, tests/hurl/blocks.hurl, tests/hurl/feetransfers.hurl, tests/hurl/next_stakes.hurl, tests/hurl/snarks.hurl, tests/hurl/stakes.hurl, tests/regression
Adds total blocks count, per epoch blocks counts, and per epoch per account blocks counts
- fixes #855
- fixes #922
=> Add block production counts

rust/src/block/store.rs, rust/src/store/column_families.rs, rust/src/store/mod.rs, rust/src/web/graphql/accounts/mod.rs, rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/next_stakes/mod.rs, rust/src/web/graphql/stakes/mod.rs, tests/hurl/accounts.hurl, tests/hurl/next_stakes.hurl, tests/hurl/stakes.hurl
=> Add per account total blocks produced to GQL endpoints

tests/hurl/blocks.hurl, tests/hurl/next_stakes.hurl, tests/hurl/stakes.hurl, tests/hurl/transactions.hurl
=> Increase duration asserts

rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/gen/mod.rs, tests/hurl/blocks.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/933
* Add correct slotSinceGenesis schema
=> Filter blocks global slot

rust/src/web/graphql/mod.rs, rust/src/web/graphql/next_stakes/mod.rs, tests/hurl/next_stakes.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/898
=> (gql) integrate next stakes with the frontend

rust/src/command/store.rs, rust/src/state/mod.rs, rust/src/store/column_families.rs, rust/src/store/fixed_keys.rs, rust/src/store/mod.rs, rust/src/web/graphql/accounts/mod.rs, rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/feetransfers/mod.rs, rust/src/web/graphql/transactions/mod.rs, rust/src/web/rest/accounts.rs, tests/hurl/accounts.hurl, tests/hurl/transaction.hurl
=> GQL indexed user command totals

rust/src/command/internal/mod.rs, rust/src/command/internal/store.rs, rust/src/command/store.rs, rust/src/state/mod.rs, rust/src/store/block_store_impl.rs, rust/src/store/column_families.rs, rust/src/store/column_families_impl.rs, rust/src/store/internal_command_store_impl.rs, rust/src/store/mod.rs, rust/src/store/user_command_store_impl.rs, rust/src/unix_socket_server.rs, rust/src/web/graphql/accounts/mod.rs, rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/feetransfers/mod.rs, rust/src/web/graphql/transactions/mod.rs, rust/tests/command/store.rs, tests/hurl/accounts.hurl, tests/hurl/feetransfers.hurl
- resolves #967 
- resolves Granola-Team/mina-block-explorer#669
=> GQL internal command totals

rust/src/ledger/store.rs, rust/src/store/column_families.rs, rust/src/store/column_families_impl.rs, rust/src/store/ledger_store_impl.rs, rust/src/store/mod.rs, rust/src/web/graphql/stakes/mod.rs, tests/hurl/stakes.hurl
=> Add staking ledger epoch index

Justfile, tests/hurl/stakes.hurl, tests/hurl_tier2/stakes.hurl, tests/regression
=> Move slow stakes queries to tier2 reg tests

rust/src/web/graphql/blocks/mod.rs, tests/hurl/blocks.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1008
=> Fix blocks gql early exit issue when filtering by `slotSinceGenesis_lte`

rust/src/block/store.rs, rust/src/store/block_store_impl.rs, rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/feetransfers/mod.rs, rust/src/web/graphql/stakes/mod.rs, rust/src/web/rest/blockchain.rs, rust/src/web/rest/blocks.rs, tests/data/json-schemas/summary.json, tests/hurl/blocks.hurl, tests/regression
- resolves #1017
- closes #1018
- adds `/blocks/height={height}` & `/blocks/slot={global_slot}` REST endpoints
=> Refactor web endpoints

rust/src/canonicity/store.rs, rust/src/command/mod.rs, rust/src/snark_work/store.rs, rust/src/state/mod.rs, rust/src/store/canonicity_store_impl.rs, rust/src/store/column_families.rs, rust/src/store/column_families_impl.rs, rust/src/store/mod.rs, rust/src/store/snark_store_impl.rs, rust/src/web/graphql/snarks/mod.rs, rust/tests/event/log.rs, tests/hurl/accounts.hurl, tests/hurl/snarks.hurl, tests/hurl/stakes.hurl
- resolves #963
- fixes panic on memo decode error https://github.com/Granola-Team/mina-indexer/pull/1022
=> Iterate via SNARK prover

rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/feetransfers/mod.rs, rust/src/web/graphql/snarks/mod.rs, rust/src/web/graphql/transactions/mod.rs, tests/hurl/blocks.hurl
- resolves #1028
- resolves #1040
=> GQL non canoncical blocks sort

rust/src/web/graphql/stakes/mod.rs, tests/hurl/stakes.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1042
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1025
* Validate the epoch from the iterator as it will continue to return data until it reaches the end
* Add usersnames
=> Fix issue where public keys aren't unique per epoch

rust/src/client.rs, rust/src/constants.rs, rust/src/event/store.rs, rust/src/ledger/genesis.rs, rust/src/store/event_store_impl.rs, rust/src/store/fixed_keys.rs, rust/src/store/mod.rs, rust/src/store/version.rs, rust/src/store/version_store_impl.rs, rust/src/unix_socket_server.rs, rust/tests/canonicity/blocks.rs, rust/tests/canonicity/ledgers.rs, rust/tests/event/log.rs, rust/tests/event/memoize_ledger.rs, rust/tests/event/replay.rs, rust/tests/event/sync.rs, rust/tests/event/witness_tree.rs, rust/tests/ledger/balance_sorted_accounts.rs, rust/tests/state/orphaned_blocks.rs, rust/tests/usernames/mod.rs, tests/regression
- resolves #1039
- resolves #921
- adds context to diagnose #1054
=> Add db version

rust/src/store/block_store_impl.rs
- adds context to diagnose #1054
=> Add context to get_block

rust/src/web/graphql/blocks/mod.rs, rust/src/web/rest/blockchain.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1060
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1058
* Correctly return slot value for the block
=> Correctly calculate the slot for blocks and summary API

rust/src/bin/mina-indexer.rs, rust/src/command/internal/store.rs, rust/src/command/store.rs, rust/src/snark_work/store.rs, rust/src/store/column_families.rs, rust/src/store/column_families_impl.rs, rust/src/store/internal_command_store_impl.rs, rust/src/store/mod.rs, rust/src/store/snark_store_impl.rs, rust/src/store/user_command_store_impl.rs, rust/src/store/username_store_impl.rs, rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/feetransfers/mod.rs, rust/src/web/rest/accounts.rs, tests/hurl/blocks.hurl, tests/regression
- resolves #891
- resolves #754
=> GQL per block data counts

rust/src/block/store.rs, rust/src/command/store.rs, rust/src/store/account_store_impl.rs, rust/src/store/block_store_impl.rs, rust/src/store/canonicity_store_impl.rs, rust/src/store/column_families.rs, rust/src/store/column_families_impl.rs, rust/src/store/ledger_store_impl.rs, rust/src/store/mod.rs, rust/src/store/user_command_store_impl.rs, rust/src/store/version.rs, rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/snarks/mod.rs, rust/src/web/graphql/stakes/mod.rs, rust/src/web/graphql/transactions/mod.rs, rust/tests/command/store.rs, tests/hurl/stakes.hurl
- resolves #1059
- resolves #1092
- fixes #1096
- fixes #1097
=> Add block height sorting

rust/src/web/graphql/accounts/mod.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1098
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1067
* Fix accounts gql crash when balance sorted accounts aren't in the best ledger
* Return username in the accounts GQL endpoint
=> Fix accounts gql crash when balance sorted accounts aren't in the best ledger

rust/src/web/rest/blockchain.rs
=> REST change summary db version to string

rust/src/web/graphql/transactions/mod.rs, tests/hurl/transactions.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1106
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1079
* Correctly query txns when filtering by `from` or `to`
* Make query and sort_by optional
=> Correctly query txns when filtering by `from` or `to`

rust/src/web/graphql/transactions/mod.rs, tests/hurl/transactions.hurl
=> GQL txn sorting

rust/src/store/block_store_impl.rs, rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/transactions/mod.rs, tests/hurl/transactions.hurl
=> GQL block sorting canonicity

flake.nix, rust/src/block/genesis.rs, rust/src/block/precomputed.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1082
* Include the mainnet genesis block in the binary
=> (chore) include the mainnet genesis block in the binary

Justfile
=> Build OCI image in tier-2 testing

.gitignore
https://www.toptal.com/developers/gitignore/api/direnv
=> chore: add .envrc to gitignore

rust/src/block/precomputed.rs, rust/src/block/store.rs, rust/src/command/mod.rs, rust/src/ledger/account/mod.rs, rust/src/ledger/mod.rs, rust/src/ledger/username.rs, rust/src/state/mod.rs, rust/src/store/user_command_store_impl.rs, rust/src/store/username.rs, rust/src/store/username_store_impl.rs, rust/src/web/graphql/accounts/mod.rs, rust/src/web/graphql/stakes/mod.rs, rust/tests/usernames/mod.rs
- resolves #1066
- starts work on #1065
=> GQL prefix search usernames

rust/src/block/precomputed.rs, rust/src/block/store.rs, rust/src/ledger/diff/mod.rs, rust/src/ledger/mod.rs, rust/src/ledger/store.rs, rust/src/store/account.rs, rust/src/store/account_store_impl.rs, rust/src/store/block_store_impl.rs, rust/src/store/column_families.rs, rust/src/store/column_families_impl.rs, rust/src/store/ledger_store_impl.rs, rust/src/store/mod.rs, rust/src/store/user_command_store_impl.rs, rust/src/store/username.rs, rust/src/store/username_store_impl.rs, rust/src/store/version_store_impl.rs, rust/tests/usernames/mod.rs
- fixes #1065
- resolves #1148
=> Fix usernames - only apply canonical

Justfile, rust/Cargo.lock, rust/Cargo.toml, rust/src/bin/mina-indexer.rs, rust/src/web/mod.rs, tests/hurl/blocks.hurl, tests/hurl/feetransfers.hurl, tests/hurl/snarks.hurl, tests/hurl/stakes.hurl, tests/regression
Removes 12 unused package dependencies from Cargo.lock.
=> Remove unused cargo dependencies

rust/Cargo.lock, rust/Cargo.toml
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1173
=> Fix broken build on macos

rust/src/ledger/staking/mod.rs, rust/src/unix_socket_server.rs, rust/src/web/graphql/stakes/mod.rs, tests/hurl/stakes.hurl
=> Aggregate delegates

rust/src/command/internal/mod.rs
=> Aggregate fee transfers by receiver

rust/src/store/mod.rs, tests/regression
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1168
* Add INDEXER_VERSION file in the RocksDB database directory
=> (ops) add indexer store version to the database dir

rust/src/snark_work/store.rs, rust/src/store/column_families.rs, rust/src/store/column_families_impl.rs, rust/src/store/mod.rs, rust/src/store/snark_store_impl.rs, rust/src/store/version.rs, rust/src/web/graphql/snarks/mod.rs, tests/hurl/snarks.hurl
Resolves: https://github.com/Granola-Team/mina-indexer/issues/1170
* Add index to slow SNARK GQL query
=> 1170 add prover height index

rust/src/command/internal/mod.rs, rust/src/web/graphql/feetransfers/mod.rs, tests/hurl/accounts.hurl, tests/hurl/feetransfers.hurl, tests/hurl/stakes.hurl
Corrects regression tests to reflect the fix
- fixes #1181
=> 1181 fix aggregate fee transfers

rust/src/web/graphql/transactions/mod.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1187
* Make sure to use the from/to index regardless of range query to speed up response
=> Make the account spotlight query performant

rust/src/web/graphql/blocks/mod.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1192
* Make accounts spotlight page fast
=> (gql) correctly calculate the upper bounds of iterator when block height lt(e) and creator account are set

.envrc, .gitignore, Justfile, README.md
Solves the problem of unclear build prerequisites. Also deletes the incorrect 'test-regression' Just recipe; 'just bt' took its place.
=> Update developer experience

rust/src/block/precomputed.rs, rust/src/ledger/account/mod.rs, rust/src/ledger/coinbase.rs, rust/src/ledger/diff/account.rs, rust/src/ledger/diff/mod.rs, rust/src/ledger/mod.rs, rust/src/store/account.rs, rust/src/store/account_store_impl.rs, rust/src/store/block_store_impl.rs, rust/tests/ledger/balance_sorted_accounts.rs, tests/hurl/accounts.hurl, tests/regression
- resolves #945
- fixes ledger calculations for coinbase receivers
=> Fix balance sorted accounts

rust/Cargo.lock, rust/Cargo.toml, rust/src/bin/mina-indexer.rs, rust/src/client.rs, rust/src/server.rs, rust/src/store/version_store_impl.rs, rust/src/unix_socket_server.rs, rust/src/web/mod.rs
=> feat: gracefully shutdown

rust/src/ledger/store.rs, rust/src/store/column_families.rs, rust/src/store/column_families_impl.rs, rust/src/store/ledger_store_impl.rs, rust/src/store/mod.rs, rust/src/web/graphql/stakes/mod.rs, tests/hurl/stakes.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1195
=> Add staking ledger accounts  count per epoch

rust/src/server.rs
=> Ingest staking ledger first

rust/src/store/account.rs, rust/src/store/account_store_impl.rs, rust/src/store/fixed_keys.rs, rust/src/store/version.rs, rust/src/web/rest/blockchain.rs
=> Get num accounts without deserializing ledger

rust/src/web/graphql/mod.rs, rust/src/web/graphql/staged_ledgers/mod.rs, tests/hurl/staged_ledger_accounts.hurl
=> GQL staged ledger accounts

.gitignore, rust/Cargo.lock, rust/Cargo.toml, rust/src/bin/mina-indexer.rs, rust/src/lib.rs, tests/regression.bash
=> feat: write running PID to file; prevent new instance if PID is running 

rust/src/bin/mina-indexer.rs, rust/src/store/mod.rs
Fixes #1241
Also fixes issue with database not waiting to be shutdown
=> fix(snapshot): include INDEXER_VERSION file

rust/src/server.rs, rust/src/store/version.rs
Fixes Granola-Team/mina-indexer#1243
=> feat: flush/compress database after ingestion

ops/regression-test, rust/src/bin/mina-indexer.rs, rust/src/block/parser.rs, rust/src/block/precomputed.rs, rust/src/client.rs, rust/src/ledger/staking/mod.rs, rust/src/server.rs, rust/src/state/mod.rs, rust/src/store/mod.rs, rust/src/unix_socket_server.rs, rust/tests/canonicity/blocks.rs, rust/tests/canonicity/ledgers.rs, rust/tests/event/log.rs, rust/tests/event/memoize_ledger.rs, rust/tests/event/replay.rs, rust/tests/event/sync.rs, rust/tests/event/witness_tree.rs, rust/tests/ledger/balance_sorted_accounts.rs, rust/tests/state/orphaned_blocks.rs, rust/tests/usernames/mod.rs, tests/regression.bash
- resolves #1033
- resolves #1035
- resolves #1203
=> Refactor cli - database commands

rust/src/bin/mina-indexer.rs, tests/regression.bash
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1265
=> Rmove PID from database directory on exit

ops/regression-test, rust/src/bin/mina-indexer.rs, rust/src/block/parser.rs, rust/src/block/precomputed.rs, rust/src/client.rs, rust/src/ledger/staking/mod.rs, rust/src/server.rs, rust/src/state/mod.rs, rust/src/store/mod.rs, rust/src/unix_socket_server.rs, rust/tests/canonicity/blocks.rs, rust/tests/canonicity/ledgers.rs, rust/tests/event/log.rs, rust/tests/event/memoize_ledger.rs, rust/tests/event/replay.rs, rust/tests/event/sync.rs, rust/tests/event/witness_tree.rs, rust/tests/ledger/balance_sorted_accounts.rs, rust/tests/state/orphaned_blocks.rs, rust/tests/usernames/mod.rs, tests/regression.bash
=> Fix database commands

rust/src/server.rs
A regression was introduced when adding support for hard linked files. Because we now listen for CREATE file signals, there is a scenario where we try to parse the file before it's finished being written to disk. Instead we should listen for the CLOSE event in the case that the file is not a hard link.
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1267
=> Fix EOF issue when ingesting staking ledgers

ops/helpers.rb, rust/src/bin/mina-indexer.rs, rust/src/client.rs, rust/src/unix_socket_server.rs, tests/regression.bash
#1269 attempted to fix #1252
This PR actually fixes the issue
=> Fix `database version` to not use domain socket

rust/src/bin/mina-indexer.rs, rust/src/server.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1277
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1276
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1275
=> Improve the startup process

rust/Cargo.lock, rust/Cargo.toml, rust/src/bin/mina-indexer.rs, rust/src/store/mod.rs
Fixes Granola-Team/mina-indexer#1283
=> fix(snapshot): buffer file writing of snapshot file; remove gzip

Justfile, tests/regression.bash
Fixes Granola-Team/mina-indexer#1086
=> feat: add (simple) load test to tier2 testing

rust/src/block/precomputed.rs, rust/src/command/mod.rs, rust/src/command/signed.rs, rust/src/ledger/account/mod.rs, rust/src/ledger/diff/account.rs, rust/src/ledger/diff/mod.rs, rust/src/ledger/mod.rs, rust/src/store/account.rs, rust/src/unix_socket_server.rs, rust/tests/command/store.rs, rust/tests/state/ledger/apply_diff.rs, rust/tests/state/ledger/diff_from_precomputed.rs
=> Fix ledger account creation fee

rust/src/ledger/account/mod.rs, rust/tests/state/ledger/apply_diff.rs, tests/hurl/accounts.hurl, tests/regression.bash
=> Fix ledger nonces

rust/src/command/signed.rs, rust/src/ledger/account/mod.rs, rust/src/ledger/genesis.rs, rust/src/ledger/mod.rs, rust/src/ledger/staking/mod.rs, rust/src/store/column_families_impl.rs, rust/src/store/mod.rs, rust/src/store/user_command_store_impl.rs, rust/src/store/version.rs, rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/transactions/mod.rs, rust/tests/ledger/balance_sorted_accounts.rs, tests/hurl/transactions.hurl
**Merge after** #1307
- resolves #1293
- resolves #1305
=> Fix txn sort by nonce

rust/src/bin/mina-indexer.rs, rust/src/chain/mod.rs, rust/src/server.rs, tests/regression.bash
=> Feat fetch new blocks

rust/src/bin/mina-indexer.rs, rust/src/server.rs, rust/src/state/mod.rs, rust/src/store/account_store_impl.rs, rust/src/store/canonicity_store_impl.rs, rust/src/store/username_store_impl.rs, tests/regression.bash
=> Fix database creation

docs/development-principles-and-practices.md
@Isaac-DeFrain @robinbb @jhult @n1tranquilla Take some time to think about and comment. Leaving in draft.
=> Add Granola development practices and principles doc

rust/src/ledger/account/mod.rs, rust/src/ledger/diff/mod.rs, rust/src/ledger/mod.rs
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1319
=> fix:(ledger) fix staking delegation nonce issue

rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/feetransfers/mod.rs, rust/src/web/graphql/gen/mod.rs, rust/src/web/graphql/mod.rs, tests/hurl/blocks.hurl, tests/regression.bash
=> Feat: GQL block producer count

rust/src/web/graphql/feetransfers/mod.rs, tests/hurl/feetransfers.hurl
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1332
=> fix: (gql) unfilter coinbase types in the feetransfers GQL API

rust/src/ledger/account/mod.rs, rust/src/ledger/diff/account.rs, rust/src/ledger/mod.rs, rust/src/store/version.rs
- add comments to the LedgerDiff system.
- clean up nanomina_to_mina conversion function
- favour continuation style fee/balance aggregation
- increment Indexer DB version
Fixes: https://github.com/Granola-Team/mina-indexer/issues/1343
=> fix:(ledger) double nonce incrementing for delegations transactions

Justfile, ops/deploy.rb
Parameterizes the web port for the server
Closes: Granola-Team/mina-block-explorer#976
=> parameterize web port for server

rust/src/command/internal/mod.rs, rust/src/ledger/coinbase.rs
Improves legibility of `Coinbase::fee_transfer` fn
Closes: https://github.com/Granola-Team/mina-indexer/issues/1352
=> Improve legibility of `Coinbase::fee_transfer` function

ops/deploy.rb, ops/indexer-ledger-normalizer.rb, ops/mina-ledger-normalizer.rb
* fix mina and indexer normalization script to use the correct ARGV
https://github.com/Granola-Team/mina-indexer/issues/1263
=> (ops) add tier3 data consistency check

rust/src/ledger/diff/account.rs, rust/src/ledger/mod.rs, rust/src/ledger/store/best.rs, rust/tests/state/ledger/diff_from_precomputed.rs
* Account creation now represented as a debit on the new account
* Closes: #1374
=> Make account creation an unbalanced debit on the new account's balance

rust/src/server.rs
Retrying parsing staking ledgers
=> (server) retry parsing staking ledgers

rust/src/client.rs, rust/src/unix_socket_server.rs, tests/regression.bash
Depends on #1380 (merge this PR after)
Add a `--memoize` flag for cli best/staged ledger commands.
Resolves #1381
=> (cli) Add ledger memoize flag

rust/src/block/parser.rs, rust/src/block/store.rs, rust/src/canonicity/mod.rs, rust/src/canonicity/store.rs, rust/src/ledger/store/best.rs, rust/src/state/mod.rs, rust/src/store/best_ledger_store_impl.rs, rust/src/store/block_store_impl.rs, rust/src/store/canonicity_store_impl.rs, rust/src/store/mod.rs, rust/src/store/staged_ledger_store_impl.rs, rust/src/store/username.rs, rust/src/store/username_store_impl.rs, rust/tests/canonicity/chain_discovery.rs, rust/tests/ledger/staged_ledger_balance_sorted_accounts.rs, rust/tests/usernames/mod.rs, tests/hurl/blocks.hurl, tests/hurl/feetransfers.hurl, tests/hurl/transactions.hurl, tests/regression.bash
This PR eliminates the duplication in finding reorg blocks for updating the db best ledger.
Resolves #1297
=> Refactor: Dedupe reorg logic

Justfile, ops/deploy.rb, rust/src/block/parser.rs, rust/src/block/store.rs, rust/src/canonicity/mod.rs, rust/src/canonicity/store.rs, rust/src/ledger/account/mod.rs, rust/src/ledger/store/best.rs, rust/src/state/mod.rs, rust/src/store/best_ledger_store_impl.rs, rust/src/store/block_store_impl.rs, rust/src/store/canonicity_store_impl.rs, rust/src/store/mod.rs, rust/src/store/staged_ledger_store_impl.rs, rust/src/store/username.rs, rust/src/store/username_store_impl.rs, rust/src/store/version.rs, rust/tests/canonicity/chain_discovery.rs, rust/tests/ledger/staged_ledger_balance_sorted_accounts.rs, rust/tests/state/ledger/apply_diff.rs, rust/tests/usernames/mod.rs, tests/hurl/blocks.hurl, tests/hurl/feetransfers.hurl, tests/hurl/transactions.hurl, tests/regression.bash
This PR fixes the off-by-1 nonce bug.
Fixes #1394
=> Fix: Nonce off-by-one

rust/src/block/parser.rs, rust/src/canonicity/canonical_chain_discovery.rs, rust/src/store/version.rs
Removed a codepath that was not used.
=> Remove unused codepath

Justfile, ops/deploy.rb, rust/src/state/mod.rs, tests/regression.bash
This PR fixes a bug in staking ledger replay and tests this functionality sooner (tier 2 - `startup_staking_ledgers`).
Fixes #1402
=> Fix: Replay staking ledgers

rust/src/block/mod.rs, rust/src/canonicity/canonical_chain_discovery.rs, rust/src/collection/bounded_stack.rs, rust/src/collection/mod.rs, rust/src/lib.rs, rust/tests/canonicity/chain_discovery.rs
Discover algorithm is refactored.
=> Discovery algorithm refactor

rust/src/command/mod.rs, rust/src/ledger/account/mod.rs, rust/src/lib.rs, rust/src/utility/functions.rs, rust/src/utility/mod.rs, rust/src/web/rest/blockchain.rs
=> Lift code from ledger to new utility module

rust/src/ledger/mod.rs, rust/src/store/version.rs
=> Remove `saturating_sub` on Amount as balances cannot be negative

ops/indexer-ledger-normalizer.rb, ops/mina-ledger-normalizer.rb
* Add delegate to the ledger comparison check
=> (devops) include delegate when comparing ledgers

ops/indexer-ledger-normalizer.rb, ops/mina-ledger-normalizer.rb
* update mina_ledger.json export to include the delegate
=> (devops) include delegate when comparing mainnet state dump and update mina_ledger.json

rust/src/block/previous_state_hash.rs
=> more robust previous_state_hash parsing

rust/src/state/mod.rs
=> remove unused function

rust/src/server.rs, rust/src/state/mod.rs, rust/tests/event/replay.rs, rust/tests/event/sync.rs, rust/tests/state/orphaned_blocks.rs
=> Remove diffs_map

rust/src/mina_blocks/v1/staged_ledger_diff/mod.rs, rust/src/store/version.rs
=> remove `staged_ledger_diffs[].completed_works[].proofs`

rust/src/state/mod.rs, rust/src/store/version.rs
=> Write account diffs for `B62qjHdYUPTHQkwDWUbDYscteT2LFj3ro1vz9fnxMyHTACe6C2fLbSd` to disk

rust/src/block/mod.rs, rust/src/ledger/staking/mod.rs, rust/src/store/version.rs, rust/src/utility/functions.rs
=> Move utility function to utilities::functions crate

rust/src/store/best_ledger_store_impl.rs, rust/src/store/block_store_impl.rs, rust/src/store/event_store_impl.rs, rust/src/store/internal_command_store_impl.rs, rust/src/store/mod.rs, rust/src/store/snark_store_impl.rs, rust/src/store/staking_ledger_store_impl.rs, rust/src/store/username_store_impl.rs, rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/snarks/mod.rs
=> Change signature of `to_be_bytes` from `Vec<u8>` to `[u8; size_of::<u32>()]`

rust/src/store/mod.rs, rust/src/store/version.rs
=> Refactor `txn_sort_key` to return array of bytes of known size

rust/src/store/block_store_impl.rs, rust/src/store/version.rs
=> Refactor `pk_block_sort_key` to return array of bytes of known size

rust/src/store/mod.rs, rust/src/store/version.rs
=> Refactor `pk_txn_sort_key` to return array of bytes of known size

rust/src/store/staking_ledger_store_impl.rs, rust/src/store/version.rs
=> Refactor `staking_ledger_keys_*` to return array of bytes of known size

rust/src/store/mod.rs, rust/src/store/version.rs
=> Refactor `pk_txn_sort_key_prefix` to return array of bytes of known size

rust/src/store/username_store_impl.rs, rust/src/store/version.rs
=> Refactor `get_pk_username` to avoid allocating a `Vec`

rust/src/store/username_store_impl.rs, rust/src/store/version.rs
=> Refactor `update_usernames` to avoid allocating `Vec`

rust/src/store/best_ledger_store_impl.rs, rust/src/store/version.rs
=> Refactor `get_pk_delegation` to avoid unecessary `Vec` allocation

rust/src/store/best_ledger_store_impl.rs, rust/src/store/version.rs
=> Refactor `add_pk_delegate` remove unecessary Vec allocation

rust/src/store/block_store_impl.rs, rust/src/store/version.rs
=> Refactor `block_global_slot_key` to return array of bytes of known size

rust/src/ledger/mod.rs
=> remove dead code

rust/src/canonicity/canonical_chain_discovery.rs, rust/src/state/mod.rs, rust/src/utility/functions.rs
This PR makes our time reporting more accurate and consistent.
=> fix: Improve remaining time estimate and display

Justfile, ops/deploy.rb, ops/helpers.rb, ops/regression-test.rb, rust/src/client.rs, rust/src/command/mod.rs, rust/src/command/signed.rs, rust/src/command/store.rs, rust/src/ledger/store/staking.rs, rust/src/store/user_command_store_impl.rs, rust/src/store/version.rs, rust/src/unix_socket_server.rs, tests/regression.bash
This PR adds a user command CSV exporter which mirrors the functionality of ME.
- #1462
=> feat: User commands CSV exporter

rust/src/ledger/store/staged.rs, rust/src/store/column_families.rs, rust/src/store/column_families_impl.rs, rust/src/store/mod.rs, rust/src/store/staged_ledger_store_impl.rs, tests/hurl/staged_ledger_accounts.hurl
This PR improves the GQL staged ledger account query handling for missing public keys.
- #1464
=> fix: GQL staged ledger accounts error

rust/Cargo.toml, rust/src/block/precomputed.rs, rust/src/lib.rs, rust/src/profiling/mod.rs, rust/src/state/mod.rs, rust/src/store/version.rs
=> Profiling on canonical ingestion

rust/src/store/best_ledger_store_impl.rs, rust/src/store/mod.rs, rust/src/store/snark_store_impl.rs, rust/src/store/version.rs
=> refactor `u64_prefix_key` to return array of bytes of known size

rust/src/store/internal_command_store_impl.rs, rust/src/store/version.rs
=> Refactor `internal_command_key` to return array of bytes of known size

rust/src/block/store.rs, rust/src/ledger/store/staged.rs, rust/src/store/block_store_impl.rs, rust/src/store/staged_ledger_store_impl.rs, rust/src/store/version.rs
A number of requests have been batched. If this results in a perf improvement, then we'll continue with it.
=> Ingest block related inserts in a batch (part 1)

rust/src/state/mod.rs
=> iterate over ingestion profiling summary and log each line

rust/src/block/store.rs, rust/src/ledger/store/staged.rs, rust/src/store/block_store_impl.rs, rust/src/store/staged_ledger_store_impl.rs, rust/src/store/version.rs
* Switch to WriteBatch
* Log out size of batch
=> Log out size of batch to figure out how to tune RocksDb

rust/src/server.rs, rust/src/store/mod.rs, rust/src/store/version.rs
=> Rocks db tuning

rust/src/ledger/account/mod.rs, rust/src/ledger/mod.rs
=> Co-locate traits of Amount alongside struct

rust/src/ledger/coinbase.rs, rust/src/state/mod.rs
Fix how coinbase is calculated from PCB.
=> fix: Use max coinbase kind to apply diff

rust/src/store/mod.rs, rust/src/store/version.rs
=> Dump stats to logs every 3 minutes

Justfile, ops/deploy.rb, ops/helpers.rb, ops/regression-test.rb, rust/src/block/parser.rs, rust/src/canonicity/canonical_chain_discovery.rs, rust/src/state/mod.rs
Adds just recipes to improve dev experience around local deploys & testing.
=> feat: Ops just recipes

rust/src/command/internal/store.rs, rust/src/store/internal_command_store_impl.rs, rust/src/unix_socket_server.rs, rust/src/web/graphql/feetransfers/mod.rs
* Instead of loading all internal commands into memory and then truncating, load only the limit
* There are several iterations taken per internal command loaded into memory, so this should have a cascading effect (in a good way)
=> Possible fix for performance issue with accounts GQL query

rust/src/command/internal/store.rs, rust/src/store/internal_command_store_impl.rs, rust/src/unix_socket_server.rs, rust/src/web/graphql/feetransfers/mod.rs, tests/hurl/feetransfers.hurl
* Strategy is to iterate and filter over internal commands until there are 'enough'
* Iteration favours lower block heights first. This could be tweaked to favour higher blocks first, if desired
=> Performance fix account GraphQL endpoint

rust/src/ledger/store/staged.rs, rust/src/store/staged_ledger_store_impl.rs, rust/src/store/version.rs
This PR avoids an unnecessary round-trip (de)serialization of accounts
- #1499
=> fix: Ledger extraction

rust/src/server.rs, rust/src/store/version.rs
=> Fix watcher on Mac OS for staking ledger directory

rust/src/block/mod.rs, rust/src/block/parser.rs, rust/src/ledger/staking/mod.rs, rust/src/ledger/staking/parser.rs, rust/src/store/version.rs
* These two issues are intertwined 
* #503 
* #502
=> Consolidate functions that parse state hash and block height

rust/src/ledger/staking/parser.rs, rust/src/server.rs, rust/src/state/mod.rs, rust/src/store/version.rs
=> Parallelize staking ledger ingestion

rust/src/ledger/account/mod.rs, rust/src/ledger/mod.rs, rust/src/store/version.rs
=> Confidently subtract lhs and rhs for Amount

rust/src/web/graphql/stakes/mod.rs
=> Add support for `stakes_lte` to `StakesQueryInput`

rust/src/command/signed.rs, rust/src/command/store.rs, rust/src/store/column_families_impl.rs, rust/src/store/mod.rs, rust/src/utility/mod.rs, rust/src/utility/store/mod.rs, rust/src/utility/txn.rs
* Related to (but does not close) #1109
=> Refactor Txn hash length and prefix references

rust/src/web/graphql/stakes/mod.rs, tests/hurl/stakes.hurl
=> Fix `stake_lte` query and add hurl tests

rust/src/block/mod.rs, rust/src/block/parser.rs, rust/src/chain/mod.rs, rust/src/event/block.rs, rust/src/event/db.rs, rust/src/event/ledger.rs, rust/src/state/branch.rs, rust/src/store/chain_store_impl.rs, rust/src/store/snark_store_impl.rs
=> Clean up displays for various hashes

Justfile, ops/deploy.rb, ops/regression-test.rb, ops/utils.rb
Introduces & refactors dev just recipes
- #1525
=> feat(ops): Add dev just recipes

rust/src/web/graphql/stakes/mod.rs
Fixes GQL `stakes` username matching.
- #1328
=> fix(gql): username matching

rust/src/block/store.rs, rust/src/store/block_store_impl.rs, rust/src/store/canonicity_store_impl.rs, rust/src/store/column_families.rs, rust/src/store/column_families_impl.rs, rust/src/store/mod.rs, rust/src/store/version.rs, rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/feetransfers/mod.rs, rust/src/web/graphql/transactions/mod.rs, tests/hurl/blocks.hurl
Adds various counts for canonical blocks in order to calculate an orphan rate.
- #1529
=> feat(gql): add more block count data

Justfile, tests/regression.bash
Removes the redundant `many_blocks` tier 2 test and renames the `release` test
=> test(tier2): remove redundant test

rust/src/block/store.rs, rust/src/store/block_store_impl.rs, rust/src/store/column_families.rs, rust/src/store/column_families_impl.rs, rust/src/store/mod.rs, rust/src/store/version.rs, rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/feetransfers/mod.rs, tests/hurl/blocks.hurl, tests/regression.bash
Adds per epoch slots produced counts.
- #1530
=> feat(gql): add per epoch slots produced counts

rust/src/web/graphql/accounts/mod.rs, tests/hurl/accounts.hurl
Adds a delegate filter to GQL `accounts`endpoint.
- #1351
=> feat(gql): filter accounts by delegate

rust/src/block/store.rs, rust/src/store/block_store_impl.rs, rust/src/store/column_families.rs, rust/src/store/column_families_impl.rs, rust/src/store/mod.rs, rust/src/store/version.rs, rust/src/utility/store/block.rs, rust/src/web/graphql/mod.rs, rust/src/web/graphql/top_stakers.rs, tests/hurl/top_stakers.hurl
Adds the GQL `topStakers` endpoint.
- #1533
=> feat(gql): add top stakers endpoint

ops/deploy.rb
=> log `BASE_DIR` in `deploy.rb`

ops/deploy.rb
On service startup, it is nice to see what web port is is using
=> Print web port for debug purposes

ops/granola-rclone.rb
=> change rclone log level to info

ops/regression-test.rb, rust/src/snark_work/mod.rs, rust/src/snark_work/store.rs, rust/src/store/canonicity_store_impl.rs, rust/src/store/column_families.rs, rust/src/store/column_families_impl.rs, rust/src/store/mod.rs, rust/src/store/snark_store_impl.rs, rust/src/store/version.rs, rust/src/unix_socket_server.rs, rust/src/utility/store/command/user.rs, rust/src/utility/store/mod.rs, rust/src/utility/store/snarks.rs, rust/src/web/graphql/mod.rs, rust/src/web/graphql/snarks/mod.rs, rust/src/web/graphql/top_snarkers.rs, rust/tests/snark_work/mod.rs, tests/hurl/top_snarkers.hurl, tests/regression.bash
Adds the GQL `topSnarkers` endpoint and supporting functionality.
- #1534
=> feat(gql): top snarkers endpoint

Justfile, ops/ci/prod, ops/deploy.rb, ops/spec/remove_proofs_spec.rb, rust/src/store/version.rs
=> Default to including non-canoical blocks when running ops/deploy.rb

ops/regression-test.rb, rust/src/block/store.rs, rust/src/canonicity/store.rs, rust/src/snark_work/store.rs, rust/src/store/best_ledger_store_impl.rs, rust/src/store/block_store_impl.rs, rust/src/store/canonicity_store_impl.rs, rust/src/store/snark_store_impl.rs, rust/src/store/username_store_impl.rs, rust/src/unix_socket_server.rs, rust/src/web/graphql/snarks/mod.rs, rust/tests/snark_work/mod.rs, tests/regression.bash
Fixes the SNARK store updates to occur on best block updates.
- #1555
=> fix(store): snark updates

rust/src/ledger/account/mod.rs, rust/src/store/best_ledger_store_impl.rs, rust/src/store/version.rs
Fixes un-application of stake delegations in store and ledger.
- #1562
=> fix: unapply delegation

rust/src/snark_work/store.rs, rust/src/store/column_families.rs, rust/src/store/column_families_impl.rs, rust/src/store/mod.rs, rust/src/store/snark_store_impl.rs, rust/src/store/version.rs, rust/src/web/graphql/top_snarkers.rs
Adds the ability to "unapply" SNARK work upon reorg
- #1561
=> feat(store): unapply SNARK work

rust/src/command/signed.rs, rust/src/constants.rs, rust/src/store/block_store_impl.rs, rust/src/store/version.rs, rust/src/web/graphql/transactions/mod.rs, rust/src/web/graphql/version/mod.rs
Corrects date time, global slot, and block height bounded GQL `transaction` queries
- #1353
- #1539
=> fix(gql): correct bounded queries

rust/src/block/store.rs, rust/src/store/block_store_impl.rs, rust/src/web/graphql/mod.rs, rust/src/web/graphql/transactions/mod.rs, rust/tests/block/store/blocks_at_slot.rs, tests/hurl/transactions.hurl
Fixes GQL `transactions` date time handling.
- #1353
=> fix(gql): transactions date time bound

Justfile, ops/regression-test.rb
=> fix(tests): regression suite should always use same build type

README.md, ops/granola-rclone.rb, ops/remove-proofs-from-pcbs.rb
=> Improve script which preserves disk space during deployment

rust/src/web/graphql/gen/mod.rs, rust/src/web/graphql/transactions/mod.rs, tests/hurl/accounts.hurl, tests/hurl/transactions.hurl
Adds `is_applied` field to GQL transaction queries & responses.
- #1207
=> feat(gql): transaction filter applied/failed

Justfile, rust/src/block/store.rs, rust/src/store/block_store_impl.rs, rust/src/store/canonicity_store_impl.rs, rust/src/store/version.rs, rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/feetransfers/mod.rs, rust/src/web/graphql/mod.rs, rust/src/web/graphql/snarks/mod.rs, rust/src/web/graphql/transactions/mod.rs, tests/hurl/blocks.hurl, tests/hurl/feetransfers.hurl, tests/hurl/transactions.hurl, tests/regression.bash
- fixes the `BlockStore::reorg_blocks` function
- corrects corresponding hurl test data
- #1590
=> fix: db canonicity determinations

rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/feetransfers/mod.rs, rust/src/web/graphql/snarks/mod.rs
Avoids unnecessary PCB deserializations when filtering by canonicity.
=> fix(gql): avoid unnecessary PCB deserializations

rust/src/command/internal/mod.rs, rust/src/web/graphql/feetransfers/mod.rs
Uses the `internal_commmands_pk_*_iterator` over ad-hoc method.
- #1572
- #1608
=> fix(gql): use pk iterator for internal commands

rust/src/store/snark_store_impl.rs, rust/src/web/graphql/accounts/mod.rs, rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/feetransfers/mod.rs, rust/src/web/graphql/mod.rs, rust/src/web/graphql/snarks/mod.rs, rust/src/web/graphql/stakes/mod.rs, rust/src/web/graphql/transactions/mod.rs, tests/hurl/snarks.hurl
Refactors GQL utilities to avoid unnecessary clones & PCB deserializations.
=> refactor(gql): avoid clones & deserializations when possible

rust/src/command/internal/mod.rs, rust/src/command/internal/store.rs, rust/src/store/canonicity_store_impl.rs, rust/src/store/internal_command_store_impl.rs, rust/src/store/version.rs, rust/src/web/graphql/blocks/mod.rs, rust/src/web/graphql/feetransfers/mod.rs, tests/hurl/accounts.hurl, tests/hurl/feetransfers.hurl, tests/hurl/stakes.hurl, tests/regression.bash
Fixes our storage of internal commands, no longer stored as constituent parts.
- #1347
=> fix(store): internal command representation

rust/src/web/graphql/feetransfers/mod.rs
Relies on query to determine an effective `limit`
Closes: #1623
=> If block height range supplied, and block is out of bounds, exit early

rust/src/web/graphql/feetransfers/mod.rs
Moves the height-bound early exit check to before any deserialization happens.
- #1623
=> fix(gql): check fee transfer height-bound early exit before deserializing

rust/src/block/precomputed.rs, rust/src/chain/mod.rs, rust/src/command/mod.rs, rust/src/command/signed.rs, rust/src/constants.rs, rust/src/ledger/coinbase.rs, rust/src/ledger/diff/account.rs, rust/src/ledger/genesis.rs, rust/src/ledger/public_key.rs, rust/src/ledger/staking/mod.rs, rust/src/mina_blocks/common.rs, rust/src/mina_blocks/v2/protocol_state/mod.rs, rust/src/mina_blocks/v2/staged_ledger_diff/mod.rs, rust/src/protocol/serialization_types/staged_ledger_diff.rs, rust/src/snark_work/mod.rs, rust/src/store/user_command_store_impl.rs, rust/src/store/version.rs, rust/src/unix_socket_server.rs, rust/src/utility/store/command/user.rs, rust/src/utility/store/mod.rs, rust/src/web/graphql/transactions/mod.rs
Adds v1/v2 variants for various types & implements PCB functions for Berkeley blocks.
- #1596
=> feat(berkeley): add precomputed block functions

rust/src/store/snark_store_impl.rs, rust/src/web/rest/blockchain.rs, tests/data/json-schemas/summary.json, tests/hurl/rest/summary.hurl, tests/regression.bash
=> index canonical snark work

rust/src/command/signed.rs, rust/src/command/signed/mod.rs, rust/src/command/signed/txn_hash.rs, rust/src/ledger/store/best.rs, rust/src/ledger/store/staged.rs, rust/src/store/column_families_impl.rs, rust/src/store/event_store_impl.rs, rust/src/store/version.rs, rust/src/utility/store/command/user.rs, rust/src/utility/store/snarks.rs, rust/src/utility/store/staking_ledger.rs, rust/src/web/graphql/transactions/mod.rs
- handles both variants of txn hashes for db keys
- refactors comments
- separates txn hash mod
- #1633
=> feat(store): handle v2 txn hash keys

rust/src/bin/mina-indexer.rs
Prints GQL server address on server start.
=> feat(bin): print GQL server address on start

rust/src/snark_work/store.rs, rust/src/store/fixed_keys.rs, rust/src/store/snark_store_impl.rs
=> Remove unused code

rust/src/command/store.rs, rust/src/store/fixed_keys.rs, rust/src/store/user_command_store_impl.rs, rust/src/store/version.rs
Indexes, but does not reveal in the API, the applied and failed user commands
#1587
=> Index applied and failed user commands

rust/src/store/fixed_keys.rs, rust/src/web/rest/blockchain.rs, tests/data/json-schemas/summary.json, tests/hurl/rest/summary.hurl
Reveals the indexed values 
Closes: #1204
=> Reveal newly indexed user commands values

rust/src/command/internal/store.rs, rust/src/store/block_store_impl.rs, rust/src/store/fixed_keys.rs, rust/src/store/internal_command_store_impl.rs, rust/src/web/rest/blockchain.rs, tests/data/json-schemas/summary.json, tests/hurl/rest/summary.hurl
=> Index and expose new canonical internal command data

rust/src/command/store.rs, rust/src/store/block_store_impl.rs, rust/src/store/fixed_keys.rs, rust/src/store/user_command_store_impl.rs, rust/src/store/version.rs, rust/src/web/rest/blockchain.rs, tests/data/json-schemas/summary.json, tests/hurl/rest/summary.hurl
=> Track canonical information for user commands

rust/src/command/internal/store.rs, rust/src/store/internal_command_store_impl.rs, rust/src/store/version.rs, tests/hurl/feetransfers.hurl, tests/hurl/rest/summary.hurl
=> Fix internal command total count

rust/src/web/graphql/transactions/mod.rs, tests/hurl/transactions.hurl
=> Fix query bounds for user commands

rust/src/store/block_store_impl.rs, rust/src/store/column_families.rs, rust/src/store/column_families_impl.rs, rust/src/store/mod.rs, rust/src/store/version.rs, rust/tests/block/store/blocks.rs
- fixes blocks state hash query
- #1652
=> fix(gql): blocks state hash query

rust/src/store/internal_command_store_impl.rs, rust/src/web/graphql/transactions/mod.rs, tests/hurl/transactions.hurl
- improves height & slot upper bound calculations for GQL transactions
- remove redundant transaction hurl tests
=> fix(gql): upper bounds calculations

Rakefile, ops/deploy-indexer.rb
=> Make hello world deployment script

Rakefile, ops/deploy-indexer.rb, ops/ingest-blocks.rb, rust/src/bin/mina-indexer.rs
=> add new 'hello world' database command: 'ingest'

docs/features/README.md, docs/features/transactions_applied_failed.md
=> docs(txns): add applied/failed txn explanation

rust/src/command/mod.rs, rust/src/command/signed/mod.rs, rust/src/ledger/public_key.rs
Improves v2 signed command hash.
- #1667
=> feat: v2 signed command conversions

rust/src/command/mod.rs, rust/src/command/signed/mod.rs, rust/src/protocol/serialization_types/staged_ledger_diff.rs
- adds v2 payment
- fixes v2 stake delegation
- adds several contextual comments to versioned types
=> feat(v2 signed command): payments & stake delegations

Justfile, rust/Cargo.lock
- adds PCB with zkapp txns
- adds `download-mina-block` just recipe
- #1672
=> chore(berkeley): add example PCB with zkapp txns

.gitattributes, .hooks/post-checkout, .hooks/post-commit, .hooks/post-merge, .hooks/pre-push, Justfile, flake.nix, rust/src/command/mod.rs, rust/src/command/signed/mod.rs, rust/src/command/signed/txn_hash.rs, rust/src/mina_blocks/v2/staged_ledger_diff/mod.rs
=> fix(v2): txn hashing

rust/src/ledger/token.rs
- adds conversions between `u64` and base 58 address token representations
- #1676
=> feat(tokens): support token id/address conversions

Justfile, ops/indexer-ledger-normalizer.rb, ops/regression-test.rb, rust/src/client.rs, rust/src/command/signed/mod.rs, rust/src/unix_socket_server.rs, tests/regression.bash
- promotes the v2 signed command hash unit test to a regression test
- adds `Hash` client command
- fixes tier 2 tests
- fixes tier 3 test
- #1679
- #1687
=> fix(tier2): make v2 txn hash regression test

rust/src/command/mod.rs, rust/src/constants.rs, rust/src/ledger/account/mod.rs, rust/src/ledger/amount.rs, rust/src/ledger/diff/account.rs, rust/src/ledger/diff/mod.rs, rust/src/ledger/genesis.rs, rust/src/ledger/mod.rs, rust/src/ledger/nonce.rs, rust/src/ledger/staking/mod.rs, rust/src/ledger/token.rs, rust/src/ledger/token/mod.rs, rust/src/ledger/token/symbol.rs, rust/src/utility/store/command/user.rs, rust/src/web/rest/blockchain.rs, rust/src/web/rest/locked_balances.rs, rust/tests/state/dangling_branches/add_all_blocks.rs
- refactors `amount`, `nonce`, & `token` mods
=> refactor(zkapp): prepare for zkapp ledger diff

rust/src/command/mod.rs, rust/src/ledger/account/mod.rs, rust/src/ledger/diff/account.rs, rust/src/ledger/diff/mod.rs, rust/src/ledger/genesis.rs, rust/src/ledger/token/symbol.rs, rust/src/mina_blocks/v2/mod.rs, rust/src/mina_blocks/v2/staged_ledger_diff/mod.rs
- implements ledger diff from zkapp commands
- tests account diff logic
- #1649
=> feat(zkapp): calculate ledger diff

rust/data/genesis_blocks/mainnet-359605-3NK4BpDSekaqsG6tx8Nse2zJchRft2JpnbvMiog55WCr5xJZaKeP.json, rust/src/block/precomputed.rs, rust/src/ledger/coinbase.rs, rust/src/ledger/diff/account.rs, rust/src/mina_blocks/common.rs, rust/src/mina_blocks/v2/mod.rs, rust/src/mina_blocks/v2/staged_ledger_diff/mod.rs, rust/src/store/best_ledger_store_impl.rs, rust/tests/ledger/token_ledger.rs
- fixes the hardfork genesis PCB's coinbase
- refactors coinbase
=> fix(v2): correct genesis pcb coinbase

rust/src/ledger/account/mod.rs, rust/src/ledger/diff/account.rs, rust/src/ledger/mod.rs, rust/src/ledger/store/best.rs, rust/src/mina_blocks/v2/mod.rs, rust/src/store/best_ledger_store_impl.rs, rust/src/store/staged_ledger_store_impl.rs, rust/src/store/version.rs
- applies account diffs in the best ledger store
- simplifies account diff apply/unapply
- #1710
=> feat(zkapp): apply account diffs in best ledger store

rust/src/ledger/diff/account.rs, rust/src/mina_blocks/v2/mod.rs, rust/src/mina_blocks/v2/zkapp/event.rs, rust/src/mina_blocks/v2/zkapp/mod.rs, rust/src/store/best_ledger_store_impl.rs, rust/src/store/column_families.rs, rust/src/store/column_families_impl.rs, rust/src/store/mod.rs, rust/src/store/version.rs, rust/src/store/zkapp/events.rs, rust/src/store/zkapp/mod.rs, rust/src/store/zkapp_store_impl/event_store_impl.rs, rust/src/store/zkapp_store_impl/mod.rs, rust/src/utility/store/zkapp/events.rs, rust/src/utility/store/zkapp/mod.rs, rust/tests/generators.rs, rust/tests/zkapps/store/events.rs, rust/tests/zkapps/store/mod.rs
- adds a `ZkappEventStore` trait
- implements the `ZkappEventStore` trait for `IndexerStore`
- adds unit tests for `ZkappEventStore` functionality
- persists events in the best ledger store
- #1706
=> feat(store): persist zkapp events in db

rust/src/ledger/account/mod.rs, rust/src/ledger/genesis.rs, rust/src/ledger/store/best.rs, rust/src/ledger/store/staged.rs, rust/src/ledger/username.rs, rust/src/server.rs, rust/src/state/mod.rs, rust/src/store/best_ledger_store_impl.rs, rust/src/store/staged_ledger_store_impl.rs, rust/src/store/version.rs, rust/src/utility/store/ledger/best.rs, rust/tests/block/store/genesis.rs, rust/tests/canonicity/blocks.rs, rust/tests/canonicity/ledgers.rs, rust/tests/command/store.rs, rust/tests/event/log.rs, rust/tests/event/memoize_ledger.rs, rust/tests/event/replay.rs, rust/tests/event/sync.rs, rust/tests/event/witness_tree.rs, rust/tests/ledger/best_ledger_balance_sorted_accounts.rs, rust/tests/ledger/staged_ledger_balance_sorted_accounts.rs, rust/tests/ledger/staking_ledger_balance_sorted_accounts.rs, rust/tests/ledger/token_ledger.rs, rust/tests/mod.rs, rust/tests/snark_work/mod.rs, rust/tests/state/orphaned_blocks.rs, rust/tests/usernames/mod.rs
- adds a temp hardfork genesis ledger for testing
- aggregates diffs for applying/unapplying in the best ledger store
- #1714
- #1716
=> test(hardfork): add hardfork genesis ledger for testing

Justfile, ops/regression-test.rb, rust/src/command/signed/mod.rs, rust/tests/ledger/token_ledger.rs, tests/regression.bash
- runs all ignored unit tests in tier 1
- removes a redundant regression test
- #1690
- #1717
=> test(tier1): run all ignored unit tests

rust/src/ledger/genesis.rs, rust/tests/command/store.rs, rust/tests/snark_work/mod.rs
Try to fix genesis ledger parsing
=> fix: genesis ledger parsing

.envrc
- Watch and reload direnv when flake.nix changes
=> direnv: Use nix if host computer has nix available
